local STRINGS = GLOBAL.STRINGS

STRINGS.ACTIONS.EA_POPUP_SCREEN = "查看"
STRINGS.ACTIONS.EA_POPUP_SCREEN_OVERRIDE = {	--AddAction接口会覆盖STRINGS.ACTIONS.AGCW_POPUP_SCREEN，因此需要人为重新覆盖回去
	GENERIC = "查看",
	PLOW_TILE_SELECT = "规划地块",
}


--命名
STRINGS.UI.CRAFTING_FILTERS.EFFICIENT_AGRICULTURE = "高效农业"


STRINGS.NAMES.EA_JINKELA = "金坷垃"
STRINGS.RECIPE_DESC.EA_JINKELA = "最好的肥料！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.EA_JINKELA = "用了金坷垃，亩产一万八！"

STRINGS.NAMES.EA_JINKELA_ASH = "金坷垃粉"
STRINGS.RECIPE_DESC.EA_JINKELA_ASH = "用来制作最好的肥料！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.EA_JINKELA_ASH = "科技的结晶，用它来解放农业生产力吧！"

STRINGS.NAMES.EA_FERTILIZER_MACHINE = "肥料制作机"
STRINGS.RECIPE_DESC.EA_FERTILIZER_MACHINE = "科学是第一生产力！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.EA_FERTILIZER_MACHINE = "变废为宝，循环利用，可持续发展！"

STRINGS.NAMES.EA_SEEDING_MACHINE = "自动播种机"
STRINGS.RECIPE_DESC.EA_SEEDING_MACHINE = "21世纪还在用手种庄稼？时代变了！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.EA_SEEDING_MACHINE = "自动化农场第一步：自动播种！"

STRINGS.NAMES.EA_FARM_PLOW_MACHINE = "便携式自动耕地机"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.EA_FARM_PLOW_MACHINE = "自动化农场第二步：自动耕地！"
STRINGS.EA_FARM_PLOW_MACHINE_DESCRIBE = "剩余燃料："

STRINGS.NAMES.EA_FARM_PLOW_MACHINE_ITEM = "便携式自动耕地机(收起)"
STRINGS.RECIPE_DESC.EA_FARM_PLOW_MACHINE_ITEM = "自动开垦，自动犁地。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.EA_FARM_PLOW_MACHINE_ITEM = "自动化农场第二步：自动耕地！"

STRINGS.NAMES.EA_HARVEST_MACHINE = "H1-单向收割机"
STRINGS.RECIPE_DESC.EA_HARVEST_MACHINE = "只能收割单向1x3地块范围内的作物"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.EA_HARVEST_MACHINE = "自动化农场第三步：自动收获！"

STRINGS.NAMES.EA_HARVEST_MACHINE2 = "H2-全面收割机"
STRINGS.RECIPE_DESC.EA_HARVEST_MACHINE2 = "可以收割附近2x2地块范围内的作物"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.EA_HARVEST_MACHINE2 = "自动化农场第三步：自动收获！"

STRINGS.NAMES.EA_SHOP = "自动贩卖机"
STRINGS.RECIPE_DESC.EA_SHOP = "用农产品来交换其他需要的物资"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.EA_SHOP = "种地也能致富！"

STRINGS.NAMES.EA_WELL = "水井"
STRINGS.RECIPE_DESC.EA_WELL = "就地取水"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.EA_WELL = "喝水不忘挖井人！"