local STRINGS = GLOBAL.STRINGS

STRINGS.EA_SEED_BUTTON = "模式1"
STRINGS.EA_SEED_BUTTON_HOVER = "按顺序将格子里的种子依次发射"
STRINGS.EA_SEED_BUTTON2 = "模式2"
STRINGS.EA_SEED_BUTTON_HOVER2 = "按照种子在格子中的位置进行播种"
STRINGS.EA_FERTILIZER_BUTTON = "生产"
STRINGS.EA_FERTILIZER_IS_FULL = "金坷垃粉已经装满了，先取出来再继续使用吧！"
STRINGS.EA_NOT_ENOUGH = "可能是包裹里的农产品不够呢…"
STRINGS.EA_GIVE_ME_BUNDLE = "忘记打包了…先打包起来再给它吧…"
STRINGS.EA_WRONG_ITEM = "这台机器不需要这种农产品…"

STRINGS.ACTIONS.TUNRON_SEEDING_MACHINE = "播种"
STRINGS.ACTIONS.TUNRON_FERTILIZER_MACHINE = "生产"

STRINGS.EA_ROTATE = "按%s旋转方向"

STRINGS.EA_PLAN_PLOW_TILES = "规划开垦地块"
STRINGS.EA_OK = "确定"
STRINGS.EA_CANCEL = "取消"

STRINGS.TILE_SELECTION_HOVERER_TEXT_SELECT = "点击或拖拽框选地块"
STRINGS.TILE_SELECTION_HOVERER_TEXT_DISELECT = "点击或拖拽取消选择"