STRINGS.ACTIONS.CASTAOE.YASUO_SWORD = "斩钢闪"

STRINGS.NAMES.YASUO_SWORD = "无鞘之刃"
STRINGS.YASUO_SWORD = "无鞘之刃"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.YASUO_SWORD = "长路漫漫，唯剑作伴"
STRINGS.RECIPE_DESC.YASUO_SWORD = "一剑，一念"