list_cloth = {
	[1] = {name = "sewing_kit", price = 400, },
	[2] = {name = "strawhat", price = 122, },
	[3] = {name = "flowerhat", price = 48, },
	[4] = {name = "grass_umbrella", price = 104, },
	[5] = {name = "umbrella", price = 168, },
	[6] = {name = "minifan", price = 84, },
	[7] = {name = "beefalohat", price = 560, },
	[8] = {name = "catcoonhat", price = 480, },
	[9] = {name = "earmuffshat", price = 96, },
	[10] = {name = "hawaiianshirt", price = 540, },
	[11] = {name = "icehat", price = 360, },
	[12] = {name = "raincoat", price = 356, },
	[13] = {name = "rainhat", price = 282, },
	[14] = {name = "reflectivevest", price = 254, },
	[15] = {name = "trunkvest_summer", price = 365, },
	[16] = {name = "trunkvest_winter", price = 543, },
	[17] = {name = "watermelonhat", price = 72, },
	[18] = {name = "winterhat", price = 246, },

	[19] = {name = "torch", price = 57, },
	[20] = {name = "redlantern", price = 124, },
	[21] = {name = "lantern", price = 135, },
	[22] = {name = "minerhat", price = 290, },
	[23] = {name = "pumpkin_lantern", price = 179, },
	[24] = {name = "molehat", price = 366, },

	[25] = {name = "beehat", price = 276, },
	[26] = {name = "featherhat", price = 348, },
	[27] = {name = "bushhat", price = 217, },
	[28] = {name = "tophat", price = 180, },
	[29] = {name = "spiderhat", price = 325, },
	[30] = {name = "goggleshat", price = 125, },
	[31] = {name = "sweatervest", price = 640, },
	[32] = {name = "onemanband", price = 380, },
	[33] = {name = "compass", price = 30, },
	[34] = {name = "waterballoon", price = 30, },
	[35] = {name = "amulet", price = 350, },
	[36] = {name = "blueamulet", price = 200, },
	[37] = {name = "purpleamulet", price = 720, },

	[38] = {name = "heatrock", price = 150, },
	[39] = {name = "bedroll_straw", price = 110, },
	[40] = {name = "bedroll_furry", price = 270, },
	[41] = {name = "bernie_inactive", price = 180, },
	[42] = {name = "giftwrap", price = 15, },
	[43] = {name = "bundlewrap", price = 260, },
	[44] = {name = "featherpencil", price = 40, },
	[45] = {name = "healingsalve", price = 65, },
	[46] = {name = "bandage", price = 100, },
	[47] = {name = "lifeinjector", price = 135, },

	[48] = {name = "backpack", price = 100, },
	[49] = {name = "piggyback", price = 540, },
	[50] = {name = "winter_ornament_light1", price = 150, },
	[51] = {name = "winter_ornament_light2", price = 150, },
	[52] = {name = "winter_ornament_light3", price = 150, },
	[53] = {name = "winter_ornament_light4", price = 150, },
	[54] = {name = "cookiecutterhat", price = 140, }, 
	[55] = {name= "sewing_tape", price = 80, },
}

list_smithing = {
	[1] = {name = "armorgrass", price = 80, },
	[2] = {name = "armorwood", price = 120, },
	[3] = {name = "spear", price = 50, },
	[4] = {name = "spear_wathgrithr", price = 130, },
	[5] = {name = "wathgrithrhat", price = 200, },
	[6] = {name = "hambat", price = 180, },
	[7] = {name = "footballhat", price = 120, },
	[8] = {name = "tentaclespike", price = 120, },
	[9] = {name = "batbat", price = 700, },
	[10] = {name = "nightsword", price = 375, },
	[11] = {name = "armor_sanity", price = 380, },
	[12] = {name = "armormarble", price = 500, },
	[13] = {name = "whip", price = 790, },
	[14] = {name = "boomerang", price = 100, },
	[15] = {name = "blowdart_pipe", price = 120, },
	[16] = {name = "blowdart_fire", price = 60, },
	[17] = {name = "blowdart_sleep", price = 75, },
	[18] = {name = "blowdart_yellow", price = 120, },
	[19] = {name = "firestaff", price = 300, },
	[20] = {name = "icestaff", price = 250, },
	[21] = {name = "telestaff", price = 840, },

	[22] = {name = "gunpowder", price = 45, },
	[23] = {name = "trap_teeth", price = 110, },
	[24] = {name = "beemine", price = 200, },

	[25] = {name = "axe", price = 40, },
	[26] = {name = "shovel", price = 40, },
	[27] = {name = "pickaxe", price = 40, },
	[28] = {name = "goldenaxe", price = 80, },
	[29] = {name = "goldenshovel", price = 80, },
	[30] = {name = "goldenpickaxe", price = 80, },
	[31] = {name = "hammer", price = 140, },
	[32] = {name = "pitchfork", price = 40, },
	[33] = {name = "razor", price = 40, },
	[34] = {name = "bugnet", price = 110, },
	[35] = {name = "birdtrap", price = 150, },
	[36] = {name = "fishingrod", price = 80, },
	[37] = {name = "saddle_basic", price = 500, },
	[38] = {name = "saddlehorn", price = 100, },

	[39] = {name = "turf_grass", price = 20, },
	[40] = {name = "turf_forest", price = 20, },
	[41] = {name = "turf_savanna", price = 20, },
	[42] = {name = "turf_deciduous", price = 20, },
	[43] = {name = "turf_rocky", price = 20, },
	[44] = {name = "turf_carpetfloor", price = 90, },
	[45] = {name = "turf_checkerfloor", price = 30, },
	[46] = {name = "turf_woodfloor", price = 60, },
	[47] = {name = "turf_road", price = 90, },

	[48] = {name = "fence_item", price = 10, },
	[49] = {name = "fence_gate_item", price = 160, },
	[50] = {name = "wall_hay_item", price = 20, },
	[51] = {name = "wall_wood_item", price = 20, },
	[52] = {name = "wall_stone_item", price = 30, },
	[53] = {name = "wall_moonrock_item", price = 150, },
	[54] = {name = "pocket_scale", price = 50, }, 
	[55] = {name = "oceanfishingrod", price = 150, }, 
	[56] = {name = "moonglassaxe", price = 210, }, 
	[57] = {name = "glasscutter", price = 330, }, 
	[58] = {name = "turf_meteor", price = 75, }, 
	[59] = {name = "bathbomb", price = 30, }, 
	[60] = {name = "halloweenpotion_moon", price = 10, }, 

	[61] = {name = "turf_underrock", price = 40, },
	[62] = {name = "turf_cave", price = 30, },
	[63] = {name = "turf_desertdirt", price = 40, },
	[64] = {name = "turf_fungus", price = 30, },
	[65] = {name = "turf_fungus_green", price = 30, },
	[66] = {name = "turf_fungus_red", price = 30, },
	[67] = {name = "turf_marsh", price = 40, },
	[68] = {name = "turf_mud", price = 50, },
	[69] = {name = "turf_pebblebeach", price = 60, },
	[70] = {name = "turf_sinkhole", price = 40, },
	[71] = {name= "moonrockidol", price = 200, },
}

list_resource = {
	[1] = {name = "cutgrass", price = 5, },
	[2] = {name = "twigs", price = 10, },
	[3] = {name = "log", price = 15, },
	[4] = {name = "charcoal", price = 10, },
	[5] = {name = "cutreeds", price = 10, },
	[6] = {name = "rocks", price = 10, },
	[7] = {name = "flint", price = 5, },
	[8] = {name = "nitre", price = 20, },
	[9] = {name = "goldnugget", price = 20, },
	[10] = {name = "marble", price = 30, },
	[11] = {name = "moonrocknugget", price = 40, },
	[12] = {name = "dug_berrybush", price = 40, },
	[13] = {name = "dug_berrybush2", price = 40, },
	[14] = {name = "dug_berrybush_juicy", price = 40, },
	[15] = {name = "dug_grass", price = 20, },
	[16] = {name = "dug_sapling", price = 30, },
	[17] = {name = "dug_marsh_bush", price = 20, },
	[18] = {name = "pinecone", price = 10, },
	[19] = {name = "acorn", price = 15, },
	[20] = {name = "twiggy_nut", price = 10, },
	[21] = {name = "seeds", price = 10, },
	[22] = {name = "foliage", price = 10, },
	[23] = {name = "succulent_picked", price = 10, },
	[24] = {name = "lightbulb", price = 10, },
	[25] = {name = "wormlight_lesser", price = 30, },
	[26] = {name = "wormlight", price = 70, },
	[27] = {name = "fireflies", price = 150, },
	[28] = {name = "redgem", price = 120, },
	[29] = {name = "bluegem", price = 120, },
	[30] = {name = "purplegem", price = 180, },
	[31] = {name = "livinglog", price = 90, },
	[32] = {name = "nightmarefuel", price = 30, },
	[33] = {name = "spidergland", price = 20, },
	[34] = {name = "silk", price = 30, },
	[35] = {name = "spidereggsack", price = 300, },
	[36] = {name = "honeycomb", price = 300, },
	[37] = {name = "coontail", price = 100, },
	[38] = {name = "boneshard", price = 20, },
	[39] = {name = "houndstooth", price = 40, },
	[40] = {name = "stinger", price = 20, },
	[41] = {name = "horn", price = 200, },
	[42] = {name = "beefalowool", price = 20, },
	[43] = {name = "pigskin", price = 50, },
	[44] = {name = "manrabbit_tail", price = 60, },
	[45] = {name = "feather_crow", price = 20, },
	[46] = {name = "feather_robin", price = 25, },
	[47] = {name = "feather_robin_winter", price = 30, },
	[48] = {name = "feather_canary", price = 50, },
	[49] = {name = "beardhair", price = 20, },
	[50] = {name = "tentaclespots", price = 80, },
	[51] = {name = "mosquitosack", price = 30, },
	[52] = {name = "batwing", price = 70, },
	[53] = {name = "rottenegg", price = 5, },
	[54] = {name = "spoiled_food", price = 10, },
	[55] = {name = "poop", price = 20, },
	[56] = {name = "guano", price = 20, },
	[57] = {name = "phlegm", price = 100, },
	[58] = {name = "glommerfuel", price = 40, },
	[59] = {name = "slurtleslime", price = 30, },
	[60] = {name = "slurtle_shellpieces", price = 60, },
	[61] = {name = "spore_medium", price = 55, },
	[62] = {name = "spore_small", price = 55, },
	[63] = {name = "spore_tall", price = 55, },
	[64] = {name = "tallbirdegg", price = 130, },
	[65] = {name = "butterfly", price = 30, },
	[66] = {name = "bee", price = 40, },
	[67] = {name = "lureplantbulb", price = 200, },
	[68] = {name = "rabbit", price = 30, },
	[69] = {name = "mole", price = 40, },
	[70] = {name = "crow", price = 30, },
	[71] = {name = "robin", price = 30, },
	[72] = {name = "robin_winter", price = 50, },
	[73] = {name = "canary", price = 80, },
	[74] = {name = "canary_poisoned", price = 140,},
	[75] = {name = "saltrock", price = 125, },
	[76] = {name = "bullkelp_root", price = 200,},
	[77] = {name = "moonbutterfly", price = 30,},
	[78] = {name = "cookiecuttershell", price = 30, }, 
	[79] = {name = "moonglass", price = 20, }, 
	[80] = {name = "driftwood_log", price = 40, }, 
	[81] = {name = "dug_rock_avocado_bush", price = 40, }, 
	[82] = {name = "dug_trap_starfish", price = 150, }, 
	[83] = {name= "waterplant_bomb", price = 75, },
	[84] = {name= "waterplant_planter", price = 500, },
}

list_precious = {
	[1] = {name = "goatmilk", price = 1000, },
	[2] = {name = "butter", price = 1600, },
	[3] = {name = "royal_jelly", price = 1200, },
	[4] = {name = "jellybean", price = 600, },

	[5] = {name = "mandrake", price = 2500, },
	[6] = {name = "bearger_fur", price = 2500, },
	[7] = {name = "deerclops_eyeball", price = 3600, },
	[8] = {name = "dragon_scales", price = 600, },
	[9] = {name = "goose_feather", price = 200, },
	[10] = {name = "deer_antler3", price = 250, },
	[11] = {name = "klaussackkey", price = 1800, },
	[12] = {name = "fossil_piece", price = 600, },
	[13] = {name = "gears", price = 400, },
	[14] = {name = "greengem", price = 1400, },
	[15] = {name = "orangegem", price = 1100, },
	[16] = {name = "yellowgem", price = 1100, },
	[17] = {name = "lavae_egg", price = 600, },
	[18] = {name = "lightninggoathorn", price = 1200, },
	[19] = {name = "minotaurhorn", price = 2500, },
	[20] = {name = "shroom_skin", price = 1600, },
	[21] = {name = "atrium_key", price = 1200, },
	[22] = {name = "shadowheart", price = 1600, },
	[23] = {name = "slurper_pelt", price = 450, },
	[24] = {name = "thulecite", price = 200, },
	[25] = {name = "steelwool", price = 800, },
	[26] = {name = "walrus_tusk", price = 1000, },
	[27] = {name = "walrushat", price = 2400, },

	[28] = {name = "armorruins", price = 2100, },
	[29] = {name = "armorslurper", price = 3500, },
	[30] = {name = "eyeturret_item", price = 4500, },
	[31] = {name = "greenstaff", price = 4500, },
	[32] = {name = "orangestaff", price = 4800, },
	[33] = {name = "yellowstaff", price = 3700, },
	[34] = {name = "nightstick", price = 1900, },
	[35] = {name = "panflute", price = 2500, },
	[36] = {name = "ruins_bat", price = 1800, },
	[37] = {name = "ruinshat", price = 1400, },
	[38] = {name = "slurtlehat", price = 1200, },
	[39] = {name = "armorsnurtleshell", price = 1800, },
	[40] = {name = "staff_tornado", price = 4000, },

	[41] = {name = "cane", price = 1000, },
	[42] = {name = "featherfan", price = 1500, },
	[43] = {name = "icepack", price = 6000, },
	[44] = {name = "opalstaff", price = 6150, },
	[45] = {name = "saddle_race", price = 1200, },
	[46] = {name = "saddle_war", price = 4800, },
	[47] = {name = "armordragonfly", price = 1400, },
	[48] = {name = "beargervest", price = 4600, },
	[49] = {name = "eyebrellahat", price = 5600, },
	[50] = {name = "greenamulet", price = 2200, },
	[51] = {name = "orangeamulet", price = 1700, },
	[52] = {name = "yellowamulet", price = 1700, },
	[53] = {name = "hivehat", price = 2000, },
	[54] = {name = "krampus_sack", price = 6150, },
	[55] = {name = "armorskeleton", price = 4000, },
	[56] = {name = "skeletonhat", price = 3200, },
	[57] = {name = "deserthat", price = 300, },
	[58] = {name = "thurible", price = 2400, },
	[59] = {name = "townportaltalisman", price = 300, },
	[60] = {name = "sleepbomb", price = 800, },
	[61] = {name = "red_mushroomhat", price = 120, },
	[62] = {name = "green_mushroomhat", price = 120, },
	[63] = {name = "blue_mushroomhat", price = 120, },
	[64] = {name = "trinket_15", price = 500, },
	[65] = {name = "trinket_16", price = 500, },
	[66] = {name = "trinket_28", price = 500, },
	[67] = {name = "trinket_29", price = 500, },
	[68] = {name = "trinket_30", price = 500, },
	[69] = {name = "trinket_31", price = 500, },
	[70] = {name = "opalpreciousgem", price = 4000, },
	[71] = {name = "malbatross_feather", price = 900, }, 
	[72] = {name = "gnarwail_horn", price = 1100, }, 
	[73] = {name = "voltgoatjelly", price = 1500, }, 
	[74] = {name = "wintersfeastfuel", price = 200, }, 
}


list_blueprint = {
	[1] = {name = "mushroom_light_blueprint", price = 2000, },
	[2] = {name = "mushroom_light2_blueprint", price = 2000, },
	[3] = {name = "bundlewrap_blueprint", price = 2000, },
	[4] = {name = "sleepbomb_blueprint", price = 2000, },
	[5] = {name = "endtable_blueprint", price = 2000, },
	[6] = {name = "dragonflyfurnace_blueprint", price = 2000, },
	[7] = {name = "townportal_blueprint", price = 2000, },
	[8] = {name = "goggleshat_blueprint", price = 2000, },
	[9] = {name = "deserthat_blueprint", price = 2000, },
	[10] = {name = "red_mushroomhat_blueprint", price = 2000, },
	[11] = {name = "green_mushroomhat_blueprint", price = 2000, },
	[12] = {name = "blue_mushroomhat_blueprint", price = 2000, },
}