GLOBAL.setmetatable(env, { __index = function(t, k) return GLOBAL.rawget(GLOBAL, k) end })
TUNING.INITIALCOIN = GetModConfigData('initialcoin')                   
TUNING.PRICERATE = GetModConfigData('pricerate')                       
TUNING.SEASONALCHANGE = GetModConfigData('seasonalchange')             
TUNING.GHOSTSHOPPING = GetModConfigData('ghostshopping')               
TUNING.EXCLUSIVEITEM = GetModConfigData('exclusiveitem')               

TUNING.recyclingprice1 = GetModConfigData('recyclingprice1')           
TUNING.recyclingprice2 = GetModConfigData('recyclingprice2')           
TUNING.Functionalsell = GetModConfigData('Functionalsell')             
TUNING.Functionalswitch = GetModConfigData('Functionalswitch')         
TUNING.umswitch = GetModConfigData('umswitch')                         
TUNING.PRICERATErecovery = GetModConfigData('recovery_t')              
TUNING.PRICERATErecoverytime = GetModConfigData('recovery_time')       
TUNING.precious_sell = GetModConfigData('precious_sell')               
TUNING.Legionswitch = GetModConfigData('Legionswitch')                 
TUNING.Legionsell = GetModConfigData('Legionsell')                     
TUNING.NDNR_SWITCH = GetModConfigData('ndnrswitch')                    
TUNING.Island_switch = GetModConfigData('Island_switch')               

TUNING.UPDATELIST = GetModConfigData('updatelist')                     

TUNING.allow_selist_special = GetModConfigData('allow_selist_special') 
TUNING.giveluckamulet = GetModConfigData('giveluckamulet')             
TUNING.givegoldstaff = GetModConfigData('givegoldstaff')               
TUNING.FIXTWOPRICE = GetModConfigData('fixtwoprice')                   
TUNING.allowgoldstaff = GetModConfigData('Disintegrate')               
TUNING.stealercandig = GetModConfigData("Dig")                         
TUNING.stealercanhammer = GetModConfigData("Hammer")                   
TUNING.Refresh_Price = 300 * TUNING.PRICERATE                          
modimport("scripts/se_locadsource.lua")                                
modimport("scripts/se_rpc.lua")                                        
modimport("scripts/se_functionse.lua")                                 
