local itemlist = {}
itemlist.selist_food_mod = {}
itemlist.selist_cloth_mod = {}
itemlist.selist_smithing_mod = {}
itemlist.selist_resource_mod = {}
itemlist.selist_precious_mod = {}

itemlist.selist_blueprint_mod = {}

itemlist.selist_food = {
    {name = "kabobs", price = 69},
    {name = "meatballs", price = 82},
    {name = "bonestew", price = 118},
    {name = "turkeydinner", price = 115},
    {name = "baconeggs", price = 91},
    {name = "perogies", price = 92},
    {name = "hotchili", price = 94},
    {name = "guacamole", price = 92},
    {name = "unagi", price = 107},
    {name = "frogglebunwich", price = 63},
    {name = "fishtacos", price = 145},
    {name = "fishsticks", price = 141},
    {name = "honeynuggets", price = 73},
    {name = "honeyham", price = 102},
    {name = "monsterlasagna", price = 99},
    {name = "powcake", price = 65},
    {name = "butterflymuffin", price = 59},
    {name = "fruitmedley", price = 94},
    {name = "ratatouille", price = 67},
    {name = "jammypreserves", price = 67},
    {name = "trailmix", price = 61},
    {name = "flowersalad", price = 92},
    {name = "taffy", price = 61},
    {name = "icecream", price = 155},
    {name = "waffles", price = 173},
    {name = "pumpkincookie", price = 86},
    {name = "stuffedeggplant", price = 77},
    {name = "watermelonicle", price = 75},
    {name = "dragonpie", price = 118},
    {name = "pepperpopper", price = 101},
    {name = "mashedpotatoes", price = 120},
    {name = "potatotornado", price = 75},
    {name = "salsa", price = 102},
    {name = "vegstinger", price = 82},
    {name = "asparagussoup", price = 79},
    {name = "surfnturf", price = 106},
    {name = "seafoodgumbo", price = 175},
    {name = "californiaroll", price = 85},
    {name = "ceviche", price = 111},
    {name = "lobsterdinner", price = 217},
    {name = "lobsterbisque", price = 127},
    {name = "barnaclestuffedfishhead", price = 84},
    {name = "barnaclinguine", price = 77},
    {name = "barnaclepita", price = 62},
    {name = "barnaclesushi", price = 73},
    {name = "sweettea", price = 63},
    {name = "koalefig_trunk", price = 176},
    {name = "figkabab", price = 78},
    {name = "figatoni", price = 69},
    {name = "frognewton", price = 65},
    {name = "meatysalad", price = 94},
    {name = "leafymeatsouffle", price = 111},
    {name = "leafymeatburger", price = 113},
    {name = "leafloaf", price = 103},
    {name = "bananapop", price = 63},
    {name = "bananajuice", price = 69},
    {name = "frozenbananadaiquiri", price = 71},
    {name = "mandrakesoup", price = 425},
    {name = "bonesoup", price = 153},
    {name = "freshfruitcrepes", price = 221},
    {name = "moqueca", price = 157},
    {name = "monstertartare", price = 144},
    {name = "voltgoatjelly", price = 500},
    {name = "glowberrymousse", price = 150},
    {name = "potatosouffle", price = 154},
    {name = "frogfishbowl", price = 138},
    {name = "gazpacho", price = 126},
    {name = "dragonchilisalad", price = 190},
    {name = "nightmarepie", price = 195},
    {name = "bunnystew", price = 73},
    {name = "justeggs", price = 85},
    {name = "veggieomlet", price = 67},
    {name = "talleggs", price = 179},
    {name = "shroomcake", price = 88},
    {name = "beefalotreat", price = 55},
    {name = "beefalofeed", price = 49},
    {name = "dustmeringue", price = 30},
    {name = "yotr_food1", price = 74},
    {name = "yotr_food2", price = 114},
    {name = "yotr_food3", price = 64},
    {name = "yotr_food4", price = 76},
    {name = "yotp_food1", price = 120},
    {name = "yotp_food3", price = 90},
    {name = "shroombait", price = 102},
    {name = "meat", price = 30},
    {name = "meat_dried", price = 60},
    {name = "monstermeat", price = 27},
    {name = "monstermeat_dried", price = 54},
    {name = "smallmeat", price = 18},
    {name = "smallmeat_dried", price = 36},
    {name = "drumstick", price = 18},
    {name = "bird_egg", price = 18},
    {name = "fishmeat_small", price = 20},
    {name = "fishmeat", price = 33},
    {name = "kelp", price = 10},
    {name = "kelp_dried", price = 20},
    {name = "barnacle", price = 14},
    {name = "fig", price = 14},
    {name = "wobster_sheller_land", price = 80},
    {name = "eel", price = 60},
    {name = "froglegs", price = 14},
    {name = "plantmeat", price = 33},
    {name = "batwing", price = 32},
    {name = "batnose", price = 33},
    {name = "goatmilk", price = 100},
    {name = "butter", price = 100},
    {name = "trunk_summer", price = 125},
    {name = "trunk_winter", price = 200},
    {name = "berries", price = 10},
    {name = "berries_juicy", price = 10},
    {name = "rock_avocado_fruit_ripe", price = 10},
    {name = "acorn_cooked", price = 10},
    {name = "cutlichen", price = 10},
    {name = "ice", price = 10},
    {name = "milkywhites", price = 30},
    {name = "red_cap", price = 11},
    {name = "green_cap", price = 12},
    {name = "blue_cap", price = 16},
    {name = "moon_cap", price = 24},
    {name = "cactus_meat", price = 19},
    {name = "cactus_flower", price = 30},
    {name = "cave_banana", price = 16},
    {name = "butterflywings", price = 10},
    {name = "moonbutterflywings", price = 20},
    {name = "moon_tree_blossom", price = 10},
    {name = "honey", price = 10},
    {name = "petals", price = 6},
    {name = "petals_evil", price = 8},
    {name = "carrot", price = 12},
    {name = "corn", price = 18},
    {name = "durian", price = 24},
    {name = "pomegranate", price = 21},
    {name = "eggplant", price = 28},
    {name = "pumpkin", price = 35},
    {name = "watermelon", price = 30},
    {name = "dragonfruit", price = 75},
    {name = "asparagus", price = 18},
    {name = "onion", price = 33, tex = "quagmire_onion.tex"},
    {name = "potato", price = 28},
    {name = "tomato", price = 24, tex = "quagmire_tomato.tex"},
    {name = "garlic", price = 21},
    {name = "pepper", price = 25},
    {name = "forgetmelots", price = 8},
    {name = "tillweed", price = 8},
    {name = "firenettles", price = 8}
}

itemlist.selist_cloth = {
    {name = "sewing_kit", price = nil},
    {name = "strawhat", price = nil},
    {name = "flowerhat", price = nil},
    {name = "rabbithat", price = nil},
    {name = "grass_umbrella", price = nil},
    {name = "umbrella", price = nil},
    {name = "minifan", price = nil},
    {name = "beefalohat", price = nil},
    {name = "catcoonhat", price = nil},
    {name = "earmuffshat", price = nil},
    {name = "hawaiianshirt", price = nil},
    {name = "icehat", price = nil},
    {name = "raincoat", price = nil},
    {name = "rainhat", price = nil},
    {name = "reflectivevest", price = nil},
    {name = "trunkvest_summer", price = nil},
    {name = "trunkvest_winter", price = nil},
    {name = "watermelonhat", price = nil},
    {name = "kelphat", price = nil},
    {name = "batnosehat", price = 175},
    {name = "winterhat", price = nil},
    {name = "nightcaphat", price = 30},
    {name = "torch", price = nil},
    {name = "redlantern", price = 124},
    {name = "lantern", price = nil},
    {name = "minerhat", price = nil},
    {name = "pumpkin_lantern", price = nil},
    {name = "molehat", price = nil},
    {name = "beehat", price = nil},
    {name = "featherhat", price = nil},
    {name = "bushhat", price = nil},
    {name = "tophat", price = nil},
    {name = "spiderhat", price = 325},
    {name = "goggleshat", price = nil},
    {name = "sweatervest", price = nil},
    {name = "onemanband", price = nil},
    {name = "compass", price = nil},
    {name = "waterballoon", price = nil},
    {name = "reviver", price = 136},
    {name = "amulet", price = nil},
    {name = "blueamulet", price = nil},
    {name = "purpleamulet", price = nil},
    {name = "heatrock", price = nil},
    {name = "bedroll_straw", price = nil},
    {name = "bedroll_furry", price = nil},
    {name = "portabletent_item", price = nil},
    {name = "bernie_inactive", price = nil},
    {name = "giftwrap", price = nil},
    {name = "bundlewrap", price = nil},
    {name = "featherpencil", price = nil},
    {name = "healingsalve", price = nil},
    {name = "tillweedsalve", price = nil},
    {name = "bandage", price = nil},
    {name = "healingsalve_acid", price = nil},
    {name = "lifeinjector", price = nil},
    {name = "reskin_tool", price = nil},
    {name = "backpack", price = nil},
    {name = "piggyback", price = nil},
    {name = "seedpouch", price = nil},
    {name = "winter_ornament_light1", price = 150},
    {name = "winter_ornament_light2", price = 150},
    {name = "winter_ornament_light3", price = 150},
    {name = "winter_ornament_light4", price = 150}
}

itemlist.selist_smithing = {
    {name = "armorgrass", price = nil},
    {name = "armorwood", price = nil},
    {name = "spear", price = nil},
    {name = "spear_wathgrithr", price = 124},
    {name = "wathgrithrhat", price = 132},
    {name = "hambat", price = nil},
    {name = "footballhat", price = nil},
    {name = "cookiecutterhat", price = nil},
    {name = "tentaclespike", price = 115},
    {name = "cutless", price = 70},
    {name = "glasscutter", price = 600},
    {name = "batbat", price = nil},
    {name = "nightsword", price = nil},
    {name = "armor_sanity", price = nil},
    {name = "armormarble", price = nil},
    {name = "whip", price = nil},
    {name = "boomerang", price = nil},
    {name = "blowdart_pipe", price = nil},
    {name = "blowdart_fire", price = nil},
    {name = "blowdart_sleep", price = nil},
    {name = "blowdart_yellow", price = nil},
    {name = "firestaff", price = nil},
    {name = "icestaff", price = nil},
    {name = "telestaff", price = nil},
    {name = "gunpowder", price = nil},
    {name = "trap_teeth", price = nil},
    {name = "beemine", price = nil},
    {name = "waterplant_bomb", price = 29},
    {name = "miniflare", price = nil},
    {name = "megaflare", price = nil},
    {name = "halloweenpotion_health_small", price = 76},
    {name = "halloweenpotion_health_large", price = 100},
    {name = "halloweenpotion_sanity_small", price = 70},
    {name = "halloweenpotion_sanity_large", price = 90},
    {name = "halloweenpotion_moon", price = 100},
    {name = "halloweenpotion_embers", price = 10},
    {name = "halloweenpotion_sparks", price = 10},
    {name = "firecrackers", price = 5},
    {name = "bathbomb", price = 70},
    {name = "rope_bridge_kit", price = nil},
    {name = "rabbitkinghorn", price = nil},
    {name = "axe", price = nil},
    {name = "shovel", price = nil},
    {name = "pickaxe", price = nil},
    {name = "goldenaxe", price = nil},
    {name = "goldenshovel", price = nil},
    {name = "goldenpickaxe", price = nil},
    {name = "moonglassaxe", price = nil},
    {name = "hammer", price = nil},
    {name = "pitchfork", price = nil},
    {name = "razor", price = nil},
    {name = "bugnet", price = nil},
    {name = "birdtrap", price = nil},
    {name = "beef_bell", price = nil},
    {name = "saddle_basic", price = nil},
    {name = "brush", price = nil},
    {name = "saddlehorn", price = nil},
    {name = "fishingrod", price = nil},
    {name = "farm_hoe", price = nil},
    {name = "golden_farm_hoe", price = nil},
    {name = "wateringcan", price = nil},
    {name = "premiumwateringcan", price = nil},
    {name = "farm_plow_item", price = nil},
    {name = "compost", price = 10},
    {name = "compostwrap", price = 70},
    {name = "fertilizer", price = 110},
    {name = "soil_amender", price = 80},
    {name = "plantregistryhat", price = nil},
    {name = "treegrowthsolution", price = nil},
    {name = "chum", price = 100},
    {name = "pocket_scale", price = nil},
    {name = "oceanfishingrod", price = nil},
    {name = "tacklecontainer", price = 200},
    {name = "supertacklecontainer", price = 500},
    {name = "oceanfishingbobber_ball", price = nil},
    {name = "oceanfishingbobber_oval", price = nil},
    {name = "oceanfishingbobber_crow", price = nil},
    {name = "oceanfishingbobber_robin", price = nil},
    {name = "oceanfishingbobber_robin_winter", price = nil},
    {name = "oceanfishingbobber_canary", price = nil},
    {name = "oceanfishingbobber_goose", price = 300},
    {name = "oceanfishingbobber_malbatross", price = 400},
    {name = "trinket_8", price = 200},
    {name = "oceanfishinglure_spoon_red", price = nil},
    {name = "oceanfishinglure_spoon_green", price = nil},
    {name = "oceanfishinglure_spoon_blue", price = nil},
    {name = "oceanfishinglure_spinner_red", price = nil},
    {name = "oceanfishinglure_spinner_green", price = nil},
    {name = "oceanfishinglure_spinner_blue", price = nil},
    {name = "oceanfishinglure_hermit_drowsy", price = 230},
    {name = "oceanfishinglure_hermit_rain", price = 200},
    {name = "oceanfishinglure_hermit_snow", price = 200},
    {name = "oceanfishinglure_hermit_heavy", price = 200},
    {name = "oar", price = nil},
    {name = "oar_driftwood", price = nil},
    {name = "oar_monkey", price = 300},
    {name = "boat_item", price = 200},
    {name = "boat_ancient_item", price = 500},
    {name = "boatpatch", price = nil},
    {name = "boat_grass_item", price = nil},
    {name = "boat_bumper_kelp_kit", price = 120},
    {name = "boat_bumper_shell_kit", price = 240},
    {name = "anchor_item", price = nil},
    {name = "mast_item", price = 350},
    {name = "steeringwheel_item", price = nil},
    {name = "mastupgrade_lamp_item", price = nil},
    {name = "mastupgrade_lightningrod_item", price = nil},
    {name = "boat_rotator_kit", price = 500},
    {name = "ocean_trawler_kit", price = 346},
    {name = "boat_magnet_kit", price = nil},
    {name = "boat_magnet_beacon", price = nil},
    {name = "boat_cannon_kit", price = nil},
    {name = "cannonball_rock_item", price = nil},
    {name = "dock_kit", price = nil},
    {name = "dock_woodposts_item", price = nil},
    {name = "turf_grass", price = nil},
    {name = "turf_forest", price = nil},
    {name = "turf_savanna", price = nil},
    {name = "turf_deciduous", price = nil},
    {name = "turf_rocky", price = nil},
    {name = "turf_desertdirt", price = nil},
    {name = "turf_marsh", price = nil},
    {name = "turf_fungus", price = nil},
    {name = "turf_fungus_red", price = nil},
    {name = "turf_fungus_green", price = nil},
    {name = "turf_fungus_moon", price = nil},
    {name = "turf_sinkhole", price = nil},
    {name = "turf_mud", price = nil},
    {name = "turf_underrock", price = nil},
    {name = "turf_cave", price = nil},
    {name = "turf_pebblebeach", price = 40},
    {name = "turf_shellbeach", price = nil},
    {name = "turf_meteor", price = 87},
    {name = "turf_monkey_ground", price = 20},
    {name = "turf_archive", price = 114},
    {name = "turf_ruinsbrick", price = nil},
    {name = "turf_ruinsbrick_glow", price = nil},
    {name = "turf_ruinstrim", price = nil},
    {name = "turf_ruinstrim_glow", price = nil},
    {name = "turf_ruinstiles", price = nil},
    {name = "turf_ruinstiles_glow", price = nil},
    {name = "turf_woodfloor", price = nil},
    {name = "turf_road", price = nil},
    {name = "turf_cotl_brick", price = nil},
    {name = "turf_cotl_gold", price = nil},
    {name = "turf_carpetfloor", price = nil},
    {name = "turf_carpetfloor2", price = nil},
    {name = "turf_checkerfloor", price = nil},
    {name = "turf_beard_rug", price = nil},
    {name = "turf_mosaic_blue", price = nil},
    {name = "turf_mosaic_grey", price = nil},
    {name = "turf_mosaic_red", price = nil},
    {name = "turf_dragonfly", price = 180},
    {name = "fence_rotator", price = nil},
    {name = "fence_item", price = nil},
    {name = "fence_gate_item", price = nil},
    {name = "wall_hay_item", price = nil},
    {name = "wall_wood_item", price = nil},
    {name = "wall_stone_item", price = nil},
    {name = "wall_moonrock_item", price = nil},
    {name = "wall_ruins_item", price = 60},
    {name = "wall_dreadstone_item", price = 480},
    {name = "wall_scrap_item", price = 480}
}

itemlist.selist_resource = {
    {name = "cutgrass", price = 5},
    {name = "rope", price = 20},
    {name = "twigs", price = 6},
    {name = "log", price = 10},
    {name = "boards", price = 45},
    {name = "charcoal", price = 6},
    {name = "ash", price = 3},
    {name = "driftwood_log", price = 34},
    {name = "cutreeds", price = 8},
    {name = "papyrus", price = 37},
    {name = "rocks", price = 8},
    {name = "cutstone", price = 29},
    {name = "flint", price = 6},
    {name = "nitre", price = 12},
    {name = "goldnugget", price = 14},
    {name = "transistor", price = 68},
    {name = "gears", price = 350},
    {name = "saltrock", price = 30},
    {name = "rock_avocado_fruit", price = 18, tex = "rock_avocado_fruit_rockhard.tex"},
    {name = "marble", price = 34},
    {name = "marblebean", price = 30},
    {name = "moonrocknugget", price = 34},
    {name = "palmcone_scale", price = 40},
    {name = "dug_berrybush", price = 41},
    {name = "dug_berrybush2", price = 51},
    {name = "dug_berrybush_juicy", price = 60},
    {name = "dug_bananabush", price = 38},
    {name = "dug_grass", price = 30},
    {name = "dug_sapling", price = 26},
    {name = "dug_sapling_moon", price = 36},
    {name = "dug_marsh_bush", price = 32},
    {name = "dug_monkeytail", price = 60},
    {name = "dug_rock_avocado_bush", price = 36},
    {name = "pinecone", price = 5},
    {name = "acorn", price = 6},
    {name = "twiggy_nut", price = 6},
    {name = "palmcone_seed", price = 36},
    {name = "lureplantbulb", price = 180},
    {name = "livingtree_root", price = 100},
    {name = "ancienttree_seed", price = 150},
    {name = "ancienttree_gem_sapling_item", price = 200},
    {name = "ancienttree_nightvision_sapling_item", price = 200},
    {name = "rock_avocado_fruit_sprout", price = 85},
    {name = "bullkelp_root", price = 51},
    {name = "waterplant_planter", price = 68},
    {name = "dug_trap_starfish", price = 188},
    {name = "seeds", price = 6},
    {name = "carrot_seeds", price = 50},
    {name = "corn_seeds", price = 50},
    {name = "potato_seeds", price = 50},
    {name = "tomato_seeds", price = 50},
    {name = "asparagus_seeds", price = 50},
    {name = "eggplant_seeds", price = 50},
    {name = "pumpkin_seeds", price = 50},
    {name = "watermelon_seeds", price = 50},
    {name = "dragonfruit_seeds", price = 50},
    {name = "durian_seeds", price = 50},
    {name = "garlic_seeds", price = 50},
    {name = "onion_seeds", price = 50},
    {name = "pepper_seeds", price = 50},
    {name = "pomegranate_seeds", price = 50},
    {name = "foliage", price = 6},
    {name = "succulent_picked", price = 10},
    {name = "lightbulb", price = 12},
    {name = "wormlight_lesser", price = 24},
    {name = "wormlight", price = 68},
    {name = "ancientfruit_nightvision", price = 136},
    {name = "fireflies", price = 84},
    {name = "lightflier", price = 101},
    {name = "ancientfruit_gem", price = 500},
    {name = "redgem", price = 100},
    {name = "bluegem", price = 100},
    {name = "purplegem", price = 200},
    {name = "moonglass", price = 100},
    {name = "livinglog", price = 40},
    {name = "nightmarefuel", price = 32},
    {name = "spidergland", price = 16},
    {name = "silk", price = 20},
    {name = "spidereggsack", price = 140},
    {name = "honeycomb", price = 120},
    {name = "beeswax", price = 130},
    {name = "waxpaper", price = 180},
    {name = "coontail", price = 100},
    {name = "furtuft", price = 62},
    {name = "boneshard", price = 20},
    {name = "houndstooth", price = 38},
    {name = "stinger", price = 18},
    {name = "cookiecuttershell", price = 52},
    {name = "messagebottleempty", price = 38},
    {name = "gelblob_bottle", price = 60},
    {name = "horn", price = 180},
    {name = "beefalowool", price = 21},
    {name = "pigskin", price = 48},
    {name = "manrabbit_tail", price = 53},
    {name = "feather_crow", price = 16},
    {name = "feather_robin", price = 18},
    {name = "feather_robin_winter", price = 22},
    {name = "feather_canary", price = 36},
    {name = "beardhair", price = 20},
    {name = "tentaclespots", price = 74},
    {name = "mosquitosack", price = 32},
    {name = "rottenegg", price = 10},
    {name = "spoiled_food", price = 6},
    {name = "poop", price = 12},
    {name = "guano", price = 7},
    {name = "spoiled_fish_small", price = 7},
    {name = "spoiled_fish", price = 8},
    {name = "phlegm", price = 30},
    {name = "glommerfuel", price = 38},
    {name = "slurtleslime", price = 30},
    {name = "slurtle_shellpieces", price = 30},
    {name = "spore_medium", price = 55},
    {name = "spore_small", price = 55},
    {name = "spore_tall", price = 55},
    {name = "tallbirdegg", price = 130},
    {name = "ghostflower", price = 200},
    {name = "butterfly", price = 16},
    {name = "moonbutterfly", price = 50},
    {name = "bee", price = 22},
    {name = "killerbee", price = 22},
    {name = "mosquito", price = 25},
    {name = "rabbit", price = 24},
    {name = "mole", price = 36},
    {name = "carrat", price = 42},
    {name = "lightcrab", price = 136},
    {name = "wobster_moonglass_land", price = 120},
    {name = "spider", price = 100},
    {name = "spider_warrior", price = 150},
    {name = "spider_water", price = 150},
    {name = "spider_hider", price = 150},
    {name = "spider_spitter", price = 300},
    {name = "spider_dropper", price = 220},
    {name = "spider_moon", price = 230},
    {name = "spider_healer", price = 520},
    {name = "crow", price = 22},
    {name = "robin", price = 33},
    {name = "robin_winter", price = 44},
    {name = "puffin", price = 48},
    {name = "canary", price = 55},
    {name = "canary_poisoned", price = 125},
    {name = "bird_mutant", price = 78},
    {name = "bird_mutant_spitter", price = 78},
    {name = "pondfish", price = 90},
    {name = "pondeel", price = 90},
    {name = "oceanfish_medium_1_inv", price = 136},
    {name = "oceanfish_medium_2_inv", price = 136},
    {name = "oceanfish_medium_3_inv", price = 136},
    {name = "oceanfish_medium_4_inv", price = 136},
    {name = "oceanfish_medium_5_inv", price = 150},
    {name = "oceanfish_medium_6_inv", price = 136},
    {name = "oceanfish_medium_7_inv", price = 150},
    {name = "oceanfish_medium_8_inv", price = 350},
    {name = "oceanfish_medium_9_inv", price = 150},
    {name = "oceanfish_small_1_inv", price = 90},
    {name = "oceanfish_small_2_inv", price = 90},
    {name = "oceanfish_small_3_inv", price = 90},
    {name = "oceanfish_small_4_inv", price = 90},
    {name = "oceanfish_small_5_inv", price = 90},
    {name = "oceanfish_small_6_inv", price = 350},
    {name = "oceanfish_small_7_inv", price = 350},
    {name = "oceanfish_small_8_inv", price = 350},
    {name = "oceanfish_small_9_inv", price = 350}
}

itemlist.selist_precious = {
    {name = "blueprint", price = 200},
    {name = "mandrake", price = 2500},
    {name = "deerclops_eyeball", price = 1600},
    {name = "eyebrellahat", price = nil},
    {name = "deer_antler3", price = 250},
    {name = "klaussackkey", price = 1800},
    {name = "goose_feather", price = 150},
    {name = "bearger_fur", price = 1800},
    {name = "icepack", price = nil},
    {name = "beargervest", price = nil},
    {name = "dragon_scales", price = 1600},
    {name = "lavae_egg", price = 600},
    {name = "armordragonfly", price = nil},
    {name = "hivehat", price = 2000},
    {name = "royal_jelly", price = 1100},
    {name = "jellybean", price = 400},
    {name = "antlionhat", price = nil},
    {name = "townportaltalisman", price = 200},
    {name = "fossil_piece", price = 600},
    {name = "armorskeleton", price = 5000},
    {name = "skeletonhat", price = 3200},
    {name = "thurible", price = 2400},
    {name = "shadowheart", price = 3000},
    {name = "sleepbomb", price = 800},
    {name = "red_mushroomhat", price = 320},
    {name = "green_mushroomhat", price = 320},
    {name = "blue_mushroomhat", price = 320},
    {name = "shroom_skin", price = 1600},
    {name = "moon_mushroomhat", price = nil},
    {name = "trinket_15", price = 270},
    {name = "trinket_16", price = 270},
    {name = "trinket_28", price = 270},
    {name = "trinket_29", price = 270},
    {name = "trinket_30", price = 270},
    {name = "trinket_31", price = 270},
    {name = "moonstorm_spark", price = 200},
    {name = "moonglass_charged", price = 220},
    {name = "moonstorm_static_item", price = 2000},
    {name = "alterguardianhat", price = 30000},
    {name = "alterguardianhatshard", price = 1000},
    {name = "chestupgrade_stacksize", price = nil},
    {name = "greengem", price = 1400},
    {name = "orangegem", price = 1100},
    {name = "yellowgem", price = 1100},
    {name = "opalpreciousgem", price = 6000},
    {name = "eyeturret_item", price = nil},
    {name = "greenstaff", price = nil},
    {name = "orangestaff", price = nil},
    {name = "yellowstaff", price = nil},
    {name = "multitool_axe_pickaxe", price = nil},
    {name = "nutrientsgoggleshat", price = nil},
    {name = "minotaurhorn", price = 2500},
    {name = "thulecite", price = 300},
    {name = "thulecite_pieces", price = 60},
    {name = "armorruins", price = nil},
    {name = "ruins_bat", price = nil},
    {name = "ruinshat", price = nil},
    {name = "nightmare_timepiece", price = nil},
    {name = "greenamulet", price = nil},
    {name = "orangeamulet", price = nil},
    {name = "yellowamulet", price = nil},
    {name = "shadow_forge_kit", price = nil},
    {name = "voidcloth", price = 400},
    {name = "voidcloth_scythe", price = nil},
    {name = "voidcloth_umbrella", price = nil},
    {name = "voidclothhat", price = nil},
    {name = "armor_voidcloth", price = nil},
    {name = "voidcloth_kit", price = nil},
    {name = "purebrilliance", price = 500},
    {name = "lunarplant_husk", price = 400},
    {name = "bomb_lunarplant", price = nil},
    {name = "staff_lunarplant", price = nil},
    {name = "sword_lunarplant", price = nil},
    {name = "armor_lunarplant", price = nil},
    {name = "lunarplanthat", price = nil},
    {name = "pickaxe_lunarplant", price = nil},
    {name = "shovel_lunarplant", price = nil},
    {name = "lunarplant_kit", price = nil},
    {name = "lunar_forge_kit", price = nil},
    {name = "monkey_mediumhat", price = 1000},
    {name = "polly_rogershat", price = nil},
    {name = "malbatross_feather", price = 350},
    {name = "malbatross_beak", price = 1000},
    {name = "gnarwail_horn", price = 650},
    {name = "messagebottle", price = 250},
    {name = "trident", price = 2000},
    {name = "horrorfuel", price = 350},
    {name = "dreadstone", price = 400},
    {name = "armordreadstone", price = nil},
    {name = "dreadstonehat", price = nil},
    {name = "beeswax_spray", price = nil},
    {name = "eyemaskhat", price = 450},
    {name = "shieldofterror", price = 4000},
    {name = "oceantreenut", price = 4000},
    {name = "krampus_sack", price = 20000},
    {name = "steelwool", price = 400},
    {name = "walrus_tusk", price = 1000},
    {name = "walrushat", price = 2400},
    {name = "nightstick", price = nil},
    {name = "panflute", price = nil},
    {name = "staff_tornado", price = nil},
    {name = "lightninggoathorn", price = 1000},
    {name = "slurper_pelt", price = 300},
    {name = "slurtlehat", price = 500},
    {name = "armorsnurtleshell", price = 800},
    {name = "armorslurper", price = nil},
    {name = "cane", price = nil},
    {name = "featherfan", price = nil},
    {name = "opalstaff", price = 5400},
    {name = "saddle_race", price = nil},
    {name = "saddle_war", price = nil},
    {name = "deserthat", price = nil},
    {name = "moonstorm_goggleshat", price = nil},
    {name = "wagpunk_bits", price = 350},
    {name = "wagpunkhat", price = nil},
    {name = "armorwagpunk", price = nil},
    {name = "wagpunkbits_kit", price = nil},
    {name = "security_pulse_cage", price = 3300},
    {name = "security_pulse_cage_full", price = 5000},
    {name = "beargerfur_sack", price = nil},
    {name = "deerclopseyeball_sentryward_kit", price = nil},
    {name = "houndstooth_blowpipe", price = nil},
    {name = "scraphat", price = 500},
    {name = "scrap_monoclehat", price = nil},
    {name = "boat_bumper_crabking_kit", price = 600},
    {name = "gelblob_storage_kit", price = nil},
    {name = "carpentry_blade_moonglass", price = nil},
    {name = "shadowheart_infused", price = 3300},
    {name = "shadow_beef_bell", price = nil},
    {name = "saddle_shadow", price = nil},
    {name = "shadow_battleaxe", price = nil},
    {name = "voidcloth_boomerang", price = nil},
    {name = "rabbitkingspear", price = 400}
}

itemlist.selist_precioustwo = {
    {name = "atrium_key", price = 3000},
    {name = "hermit_pearl", price = 5000},
    {name = "terrarium", price = 5000},
    {name = "moonrockseed", price = 4000}
}

itemlist.selist_special = {
    {name = "luckamulet", price = 1000},
    {name = "goldstaff", price = 1000},
    {name = "stealer", price = 7000},
    {name = "vipcard", price = 10000}
}

itemlist.selist_blueprint = {
    {name = "mushroom_light_blueprint", price = 2000},
    {name = "mushroom_light2_blueprint", price = 2000},
    {name = "red_mushroomhat_blueprint", price = 2000},
    {name = "green_mushroomhat_blueprint", price = 2000},
    {name = "blue_mushroomhat_blueprint", price = 2000},
    {name = "sleepbomb_blueprint", price = 2000},
    {name = "bundlewrap_blueprint", price = 2000},
    {name = "endtable_blueprint", price = 2000},
    {name = "dragonflyfurnace_blueprint", price = 2000},
    {name = "townportal_blueprint", price = 2000},
    {name = "antlionhat_blueprint", price = 2000},
    {name = "deserthat_blueprint", price = 2000},
    {name = "moonstorm_goggleshat_blueprint", price = 2000},
    {name = "moon_device_construction1_blueprint", price = 2000},
    {name = "archive_resonator_item_blueprint", price = 2000},
    {name = "turfcraftingstation_blueprint", price = 2000},
    {name = "refined_dust_blueprint", price = 2000},
    {name = "trident_blueprint", price = 2000},
    {name = "winch_blueprint", price = 2000},
    {name = "pirate_flag_pole_blueprint", price = 2000},
    {name = "boat_cannon_kit_blueprint", price = 2000},
    {name = "cannonball_rock_item_blueprint", price = 2000},
    {name = "dock_kit_blueprint", price = 2000},
    {name = "dock_woodposts_item_blueprint", price = 2000},
    {name = "turf_monkey_ground_blueprint", price = 2000},
    {name = "turf_shellbeach_blueprint", price = 2000},
    {name = "turf_archive_blueprint", price = 2000},
    {name = "turf_ruinsbrick_blueprint", price = 2000},
    {name = "turf_ruinsbrick_glow_blueprint", price = 2000},
    {name = "turf_ruinstrim_blueprint", price = 2000},
    {name = "turf_ruinstrim_glow_blueprint", price = 2000},
    {name = "turf_ruinstiles_blueprint", price = 2000},
    {name = "turf_ruinstiles_glow_blueprint", price = 2000},
    {name = "armordreadstone_blueprint", price = 2000},
    {name = "dreadstonehat_blueprint", price = 2000},
    {name = "wall_dreadstone_item_blueprint", price = 2000},
    {name = "support_pillar_dreadstone_scaffold_blueprint", price = 2000},
    {name = "support_pillar_scaffold_blueprint", price = 2000},
    {name = "ruinsrelic_table_blueprint", price = 2000},
    {name = "ruinsrelic_chair_blueprint", price = 2000},
    {name = "ruinsrelic_vase_blueprint", price = 2000},
    {name = "ruinsrelic_chipbowl_blueprint", price = 2000},
    {name = "ruinsrelic_bowl_blueprint", price = 2000},
    {name = "ruinsrelic_plate_blueprint", price = 2000},
    {name = "carpentry_station_blueprint", price = 2000},
    {name = "wagpunkhat_blueprint", price = 2000},
    {name = "armorwagpunk_blueprint", price = 2000},
    {name = "wagpunkbits_kit_blueprint", price = 2000},
    {name = "cotl_tabernacle_level1_blueprint", price = 2000},
    {name = "turf_cotl_brick_blueprint", price = 2000},
    {name = "turf_cotl_gold_blueprint", price = 2000},
    {name = "chestupgrade_stacksize_blueprint", price = 2000}
}

ForbiddenItems = {
    "moon_altar_icon",
    "moon_altar_ward",
    "moon_altar_glass",
    "moon_altar_seed",
    "moon_altar_idol",
    "moon_altar_crown",
    "chester_eyebone",
    "hutch_fishbowl",
    "fruitflyfruit",
    "glommerflower",
    "packim_fishbone",
    "rawling",
    "sunken_boat_trinket_4"
}

allowone = {
    "sweet_potato_oversized",
    "carrot_oversized",
    "corn_oversized",
    "durian_oversized",
    "pomegranate_oversized",
    "eggplant_oversized",
    "pumpkin_oversized",
    "watermelon_oversized",
    "dragonfruit_oversized",
    "asparagus_oversized",
    "onion_oversized",
    "potato_oversized",
    "tomato_oversized",
    "garlic_oversized",
    "pepper_oversized"
}

allowtwo = {
    "vipcard",
    "luckamulet"
}

itemlist.price_basa = {
    {name = "sweet_potato_oversized", price = 333},
    {name = "carrot_oversized", price = 333},
    {name = "corn_oversized", price = 333},
    {name = "durian_oversized", price = 333},
    {name = "pomegranate_oversized", price = 333},
    {name = "eggplant_oversized", price = 356},
    {name = "pumpkin_oversized", price = 408},
    {name = "watermelon_oversized", price = 408},
    {name = "dragonfruit_oversized", price = 458},
    {name = "asparagus_oversized", price = 333},
    {name = "onion_oversized", price = 418},
    {name = "potato_oversized", price = 356},
    {name = "tomato_oversized", price = 333},
    {name = "garlic_oversized", price = 333},
    {name = "pepper_oversized", price = 333}
}

itemlist.selist_foodum = {
    {name = "fishmeat_dried", price = 70},
    {name = "smallfishmeat_dried", price = 40},
    {name = "monstersmallmeat", price = 15},
    {name = "scorpioncarapace", price = 18, atl = "images/inventoryimages/scorpioncarapace.xml"},
    {name = "um_monsteregg", price = 17},
    {name = "rice", price = 15},
    {name = "giant_blueberry", price = 20},
    {name = "viperfruit", price = 36},
    {name = "zaspberry", price = 36},
    {name = "greenfoliage", price = 8},
    {name = "beefalowings", price = 160},
    {name = "blueberrypancakes", price = 100},
    {name = "californiaking", price = 120},
    {name = "um_deviled_eggs", price = 70},
    {name = "devilsfruitcake", price = 100},
    {name = "viperjam", price = 120},
    {name = "hardshelltacos", price = 100},
    {name = "liceloaf", price = 70},
    {name = "seafoodpaella", price = 150},
    {name = "simpsalad", price = 20},
    {name = "snotroast", price = 180},
    {name = "snowcone", price = 20},
    {name = "purplesteamedhams", price = 90},
    {name = "theatercorn", price = 80},
    {name = "stuffed_peeper_poppers", price = 150},
    {name = "zaspberryparfait", price = 150},
    {name = "honey_log", price = 120}
}
itemlist.selist_clothum = {
    {name = "snowgoggles", price = 1100},
    {name = "gasmask", price = 2400},
    {name = "plaguemask", price = 3000},
    {name = "hat_ratmask", price = 564},
    {name = "brine_balm", price = 80},
    {name = "sludge_sack", price = 816},
    {name = "sporepack", price = 1968},
    {name = "floral_bandage", price = 90}
}

itemlist.selist_smithingum = {
    {name = "rat_whip", price = 117},
    {name = "bugzapper", price = 190},
    {name = "um_bear_trap_equippable_tooth", price = 139},
    {name = "um_bear_trap_equippable_gold", price = 150},
    {name = "um_magnerang", price = 1600},
    {name = "iceboomerang", price = 150},
    {name = "um_blowdart_pyre", price = 80},
    {name = "pied_piper_flute", price = 100},
    {name = "uncompromising_blowgun", price = 500},
    {name = "blowgunammo_tooth", price = 102},
    {name = "blowgunammo_fire", price = 67},
    {name = "blowgunammo_electric", price = 75},
    {name = "um_armor_pyre_nettles", price = 72},
    {name = "armor_reed_um", price = 98},
    {name = "armor_sharksuit_um", price = 648},
    {name = "watermelon_lantern", price = 136},
    {name = "saltpack", price = 732},
    {name = "uncompromising_fishingnet", price = 80},
    {name = "driftwoodfishingrod", price = 242},
    {name = "sludge_oil", price = 190},
    {name = "boat_bumper_sludge_kit", price = 136},
    {name = "cannonball_sludge_item", price = 30},
    {name = "boatpatch_sludge", price = 225},
    {name = "mastupgrade_windturbine_item", price = 232},
    {name = "portableboat_item", price = 124},
    {name = "diseasecurebomb", price = 211},
    {name = "ratpoisonbottle", price = 124},
    {name = "turf_ancienthoodedturf", price = 36},
    {name = "turf_hoodedmoss", price = 36}
}

itemlist.selist_resourceum = {
    {name = "rat_tail", price = 20},
    {name = "sludge", price = 40},
    {name = "aphid", price = 35},
    {name = "um_smolder_spore", price = 70},
    {name = "rockjawleather", price = 200},
    {name = "woodpecker", price = 36},
    {name = "sludge_cork", price = 93},
    {name = "whisperpod", price = 100},
    {name = "spider_trapdoor", price = 210},
    {name = "skeletonmeat", price = 100},
    {name = "moon_tear", price = 300}
}

itemlist.selist_preciousum = {
    {name = "rne_goodiebag", price = 500},
    {name = "ancient_amulet_red", price = nil},
    {name = "armor_glassmail", price = nil},
    {name = "the_real_charles_t_horse", price = 3600},
    {name = "shadow_crown", price = 1000},
    {name = "skullflask", price = 1000},
    {name = "widowsgrasp", price = 1000},
    {name = "widowshead", price = 1000},
    {name = "shroom_skin_fragment", price = 330},
    {name = "glass_scales", price = 2000},
    {name = "moonglass_geode", price = 1500},
    {name = "sunglasses", price = 500},
    {name = "klaus_amulet", price = 700},
    {name = "beargerclaw", price = 700},
    {name = "gore_horn_hat", price = 600},
    {name = "um_beegun", price = 700},
    {name = "feather_frock", price = 500},
    {name = "crabclaw", price = 1000},
    {name = "slobberlobber", price = 1000},
    {name = "cursed_antler", price = 1000},
    {name = "staff_starfall", price = 2000, atl = "images/inventoryimages/staff_starfall.xml"},
    {name = "rain_horn", price = 2000},
    {name = "dormant_rain_horn", price = 500}
}

itemlist.selist_blueprintum = {
    {name = "alterguardianhatshard_blueprint", price = 2000},
    {name = "moonstorm_static_item_blueprint", price = 2000},
    {name = "skullchest_child_blueprint", price = 2000}
}

itemlist.selist_smithing_xz = {
    {name = "spice_jelly", price = 81},
    {name = "spice_voltjelly", price = 202},
    {name = "spice_phosphor", price = 100},
    {name = "spice_moontree_blossom", price = 88},
    {name = "spice_cactus_flower", price = 86},
    {name = "spice_blood_sugar", price = 110},
    {name = "spice_rage_blood_sugar", price = 252},
    {name = "spice_soul", price = 82},
    {name = "spice_potato_starch", price = 102},
    {name = "spice_poop", price = 85},
    {name = "spice_plantmeat", price = 102},
    {name = "spice_mandrake_jam", price = 352},
    {name = "spice_pomegranate", price = 127},
    {name = "spices_box", price = 612},
    {name = "closed_book", price = 88},
    {name = "xinhua_dictionary", price = 1320},
    {name = "trapreset_book", price = 280},
    {name = "marbleaxe", price = 170},
    {name = "marblepickaxe", price = 170},
    {name = "medal_farm_plow_item", price = 480},
    {name = "medal_waterpump_item", price = 2200},
    {name = "medal_rain_bomb", price = 128},
    {name = "medal_clear_up_bomb", price = 105},
    {name = "medal_moonglass_shovel", price = 432},
    {name = "medal_moonglass_hammer", price = 432},
    {name = "medal_moonglass_bugnet", price = 600},
    {name = "medal_moonglass_potion", price = 204},
    {name = "bottled_moonlight", price = 200},
    {name = "medal_naughtybell", price = 746},
    {name = "autotrap_book", price = 800},
    {name = "medal_tentaclespike", price = 500},
    {name = "trap_bat", price = 79},
    {name = "armor_medal_obsidian", price = 408},
    {name = "armor_blue_crystal", price = 444},
    {name = "bottled_soul", price = 55},
    {name = "medal_fishingrod", price = 864},
    {name = "medal_resonator_item", price = 600},
    {name = "lureplant_rod", price = 504},
    {name = "medal_skin_staff", price = 800},
    {name = "medal_chum", price = 120},
    {name = "medal_ammo_box", price = 628},
    {name = "medalslingshotammo_sanityrock", price = 84},
    {name = "medalslingshotammo_sandspike", price = 96},
    {name = "medalslingshotammo_water", price = 20},
    {name = "medalslingshotammo_devoursoul", price = 50},
    {name = "medalslingshotammo_taunt", price = 12},
    {name = "medalslingshotammo_spines", price = 25},
    {name = "friendly_certificate", price = 800},
    {name = "arrest_certificate", price = 528},
    {name = "smallminer_certificate", price = 153},
    {name = "cook_certificate", price = 862},
    {name = "smallchop_certificate", price = 240},
    {name = "handy_test_certificate", price = 792},
    {name = "wisdom_test_certificate", price = 528},
    {name = "plant_certificate", price = 1700},
    {name = "smallfishing_certificate", price = 528},
    {name = "medal_box", price = 423}
}

itemlist.selist_resource_xz = {
    {name = "toil_money", price = 100},
    {name = "medal_fishbones", price = 15},
    {name = "mandrakeberry", price = 100},
    {name = "medal_weed_seeds", price = 50},
    {name = "medal_ivy", price = 60},
    {name = "lavaeel", price = 110},
    {name = "medal_obsidian", price = 100},
    {name = "medal_blue_obsidian", price = 110},
    {name = "sanityrock_fragment", price = 100},
    {name = "medaldug_fruit_tree_stump", price = 100},
    {name = "medaldug_livingtree_root", price = 100},
    {name = "medal_monster_essence", price = 260},
    {name = "medal_glommer_essence", price = 182},
    {name = "medal_dustmothden_base", price = 300}
}

itemlist.selist_precious_xz = {
    {name = "down_filled_coat", price = 5400},
    {name = "hat_blue_crystal", price = 1872},
    {name = "medal_spacetime_bomb", price = 5500},
    {name = "mandrake_seeds", price = 1500},
    {name = "medal_goathat", price = 3500},
    {name = "immortal_fruit", price = 600},
    {name = "immortal_fruit_oversized", price = 2900},
    {name = "immortal_gem", price = 10000},
    {name = "immortal_staff", price = 16000},
    {name = "sanityrock_mace", price = 2800},
    {name = "meteor_staff", price = 2800},
    {name = "medal_losswetpouch", price = 600, tex = "wetpouch.tex"},
    {name = "medal_spacetime_lingshi", price = 1000},
    {name = "medal_withered_heart", price = 8000},
    {name = "medal_withered_royaljelly", price = 1350},
    {name = "spice_withered_royal_jelly", price = 3700},
    {name = "medal_spacetime_snacks", price = 4500},
    {name = "medal_spacetime_crystalball", price = 22000},
    {name = "medal_spacetime_potion", price = 648},
    {name = "medal_spacetime_runes", price = 1500},
    {name = "medal_time_slider", price = 500},
    {name = "medal_space_gem", price = 15000},
    {name = "devour_staff", price = 5000},
    {name = "medal_space_staff", price = 22000},
    {name = "medal_dustmeringue", price = 2100},
    {name = "medal_gift_fruit", price = 600},
    {name = "medal_gift_fruit_oversized", price = 2900},
    {name = "medal_shadow_tool", price = 4000}
}

itemlist.selist_precious_xzxz = {
    {name = "blank_certificate", price = 1000},
    {name = "speed_certificate", price = 5000},
    {name = "space_certificate", price = 18000},
    {name = "space_time_certificate", price = 35000},
    {name = "bosom_friend_certificate", price = 8000},
    {name = "justice_certificate", price = 10000},
    {name = "merm_certificate", price = 5000},
    {name = "valkyrie_examine_certificate", price = 800},
    {name = "valkyrie_test_certificate", price = 5800},
    {name = "valkyrie_certificate", price = 10000},
    {name = "naughty_certificate", price = 5000},
    {name = "multivariate_certificate", price = 1000},
    {name = "medium_multivariate_certificate", price = 2500},
    {name = "large_multivariate_certificate", price = 6000},
    {name = "inherit_certificate", price = 1500},
    {name = "down_filled_coat_certificate", price = 3200},
    {name = "blue_crystal_certificate", price = 2000},
    {name = "ommateum_certificate", price = 5000},
    {name = "treadwater_certificate", price = 5000},
    {name = "tentacle_certificate", price = 5000},
    {name = "spider_certificate", price = 5000},
    {name = "silence_certificate", price = 5000},
    {name = "bathingfire_certificate", price = 5000},
    {name = "devour_soul_certificate", price = 5000},
    {name = "medium_devour_soul_certificate", price = 10000},
    {name = "large_devour_soul_certificate", price = 27000},
    {name = "bee_king_certificate", price = 9000},
    {name = "mediumfishing_certificate", price = 5528},
    {name = "largefishing_certificate", price = 8000},
    {name = "childishness_certificate", price = 5000},
    {name = "childlike_certificate", price = 8000},
    {name = "chef_certificate", price = 5000},
    {name = "headchef_certificate", price = 8000},
    {name = "mediumchop_certificate", price = 4000},
    {name = "largechop_certificate", price = 8000},
    {name = "mediumminer_certificate", price = 4000},
    {name = "largeminer_certificate", price = 8000},
    {name = "handy_certificate", price = 7000},
    {name = "wisdom_certificate", price = 5000},
    {name = "transplant_certificate", price = 7000},
    {name = "harvest_certificate", price = 7000},
    {name = "shadowmagic_certificate", price = 20000}
}

itemlist.selist_blueprint_xz = {
    {name = "bearger_chest_blueprint", price = 2000},
    {name = "medal_cookpot_blueprint", price = 2000},
    {name = "immortal_gem_blueprint", price = 2000},
    {name = "medal_monster_essence_blueprint", price = 2000},
    {name = "medal_goathat_blueprint", price = 2000},
    {name = "trap_bat_blueprint", price = 2000},
    {name = "medal_firepit_obsidian_blueprint", price = 2000},
    {name = "medal_coldfirepit_obsidian_blueprint", price = 2000},
    {name = "armor_medal_obsidian_blueprint", price = 2000},
    {name = "armor_blue_crystal_blueprint", price = 2000},
    {name = "medal_ice_machine_blueprint", price = 2000},
    {name = "medal_seapond_blueprint", price = 2000}
}

itemlist.selist_food_lj = {
    {name = "dish_lovingrosecake", price = 184},
    {name = "dish_friedfishwithpuree", price = 365},
    {name = "dish_sosweetjarkfruit", price = 61},
    {name = "dish_murmurananas", price = 101},
    {name = "dish_wrappedshrimppaste", price = 162},
    {name = "dish_braisedmeatwithfoliages", price = 55},
    {name = "dish_farewellcupcake", price = 69},
    {name = "dish_sugarlesstrickmakercupcakes", price = 138},
    {name = "dish_merrychristmassalad", price = 60},
    {name = "dish_shyerryjam", price = 105},
    {name = "dish_duriantartare", price = 104},
    {name = "dish_ricedumpling", price = 77},
    {name = "dish_bananamousse", price = 57},
    {name = "dish_medicinalliquor", price = 118, atl = "images/inventoryimages/dish_medicinalliquor.xml"},
    {name = "dish_pomegranatejelly", price = 81},
    {name = "dish_roastedmarshmallows", price = 77},
    {name = "dish_fishjoyramen", price = 96},
    {name = "dish_neworleanswings", price = 118},
    {name = "dish_frenchsnailsbaked", price = 83},
    {name = "dish_beggingmeat", price = 47},
    {name = "dish_fleshnapoleon", price = 91},
    {name = "dish_orchidcake", price = 75},
    {name = "dish_twistedrolllily", price = 101},
    {name = "dish_chilledrosejuice", price = 89},
    {name = "dish_mushedeggs", price = 80},
    {name = "dish_l_mooncake", price = 90},
    {name = "dish_l_flowerbun", price = 70},
    {name = "dish_mushedkoi", price = 100},
    {name = "dish_mushedmilk", price = 50},
    {name = "albicans_cap", price = 45},
    {name = "shyerry", price = 50},
    {name = "mint_l", price = 15},
    {name = "pineananas", price = 20},
    {name = "squamousfruit", price = 35},
    {name = "monstrain_leaf", price = 25},
    {name = "petals_orchid", price = 17},
    {name = "petals_lily", price = 16},
    {name = "petals_rose", price = 18}
}

itemlist.selist_cloth_lj = {
    {name = "hat_cowboy", price = nil},
    {name = "hat_mermbreathing", price = nil},
    {name = "theemperorspendant", price = nil},
    {name = "theemperorsscepter", price = nil},
    {name = "theemperorsmantle", price = nil},
    {name = "theemperorscrown", price = nil},
    {name = "sachet", price = nil},
    {name = "hat_lichen", price = nil},
    {name = "giantsfoot", price = nil}
}

itemlist.selist_smithing_lj = {
    {name = "dish_tomahawksteak", price = 350},
    {name = "guitar_whitewood", price = nil},
    {name = "triplegoldenshovelaxe", price = nil},
    {name = "tripleshovelaxe", price = nil},
    {name = "dualwrench", price = nil},
    {name = "fishhomingtool_normal", price = nil},
    {name = "lance_carrot_l", price = 1000},
    {name = "shield_l_log", price = nil},
    {name = "explodingfruitcake", price = nil},
    {name = "pinkstaff", price = nil},
    {name = "mat_whitewood_item", price = nil},
    {name = "carpet_plush_big", price = 48},
    {name = "carpet_plush", price = 96}
}

itemlist.selist_resource_lj = {
    {name = "insectshell_l", price = 26},
    {name = "ahandfulofwings", price = 25},
    {name = "merm_scales", price = 28},
    {name = "raindonate", price = 55},
    {name = "shyerrylog", price = 40},
    {name = "pineananas_seeds", price = 50},
    {name = "dug_monstrain", price = 100},
    {name = "cattenball", price = 200},
    {name = "cutted_orchidbush", price = 500},
    {name = "cutted_lilybush", price = 500},
    {name = "cutted_rosebush", price = 500},
    {name = "dug_orchidbush", price = 100},
    {name = "dug_lilybush", price = 100},
    {name = "dug_rosebush", price = 100}
}

itemlist.selist_precious_lj = {
    {name = "siving_derivant_item", price = 4000},
    {name = "siving_rocks", price = 200},
    {name = "siving_feather_fake", price = 1500},
    {name = "siving_ctlwater_item", price = 5616},
    {name = "siving_ctldirt_item", price = 5616},
    {name = "siving_ctlall_item", price = 14000},
    {name = "siving_soil_item", price = 1875},
    {name = "siving_feather_real", price = 14640},
    {name = "siving_mask_gold", price = 6004},
    {name = "siving_mask", price = 3200},
    {name = "siving_mask", price = 4800},
    {name = "tourmalineshard", price = 400},
    {name = "tourmalinecore", price = 7200},
    {name = "hat_elepheetle", price = 2223},
    {name = "armor_elepheetle", price = 3276},
    {name = "boltwingout", price = 1080},
    {name = "fimbul_axe", price = 3000},
    {name = "foliageath", price = 3000},
    {name = "orchitwigs", price = 2000},
    {name = "lileaves", price = 2000},
    {name = "rosorns", price = 2000},
    {name = "neverfade", price = 6240},
    {name = "backcub", price = 4000},
    {name = "hiddenmoonlight_item", price = 636},
    {name = "revolvedmoonlight_item", price = 3146},
    {name = "fishhomingtool_awesome", price = 500},
    {name = "icire_rock", price = 888},
    {name = "hat_albicans_mushroom", price = 1440},
    {name = "shield_l_sand", price = 2028},
    {name = "guitar_miguel", price = 3258},
    {name = "acc_l_shadowmirror", price = 2000},
    {name = "soul_contracts", price = 3000},
    {name = "shyerrycore_item", price = 3000}
}
itemlist.selist_precious_ljlj = {
    {name = "refractedmoonlight", price = 20000},
    {name = "agronssword", price = 20000}
}

itemlist.selist_blueprint_lj = {
    {name = "hiddenmoonlight_item_blueprint", price = 2000},
    {name = "revolvedmoonlight_item_blueprint", price = 2000},
    {name = "siving_feather_real_blueprint", price = 2000}
}

itemlist.selist_food_ndnr = {
    {name = "ndnr_chinesefood", price = 113},
    {name = "ndnr_mushroom_wine", price = 96},
    {name = "ndnr_snakewine", price = 200},
    {name = "ndnr_dragoonheartlavaeegg", price = 1245},
    {name = "ndnr_figpudding", price = 109},
    {name = "ndnr_scallopsoup", price = 135},
    {name = "ndnr_dongpopork", price = 103},
    {name = "ndnr_tomato_egg", price = 113},
    {name = "ndnr_pineapplebun", price = 191},
    {name = "ndnr_haagendazs", price = 375},
    {name = "ndnr_stewedmushroom", price = 88},
    {name = "ndnr_steamedporkdumplings", price = 105},
    {name = "ndnr_coconutchicken", price = 84},
    {name = "ndnr_balut", price = 179},
    {name = "ndnr_shrimppullegg", price = 151},
    {name = "ndnr_wonton", price = 103},
    {name = "ndnr_kopiluwak", price = 125},
    {name = "ndnr_puff", price = 113},
    {name = "ndnr_yogurt", price = 105},
    {name = "ndnr_seatreasure", price = 212},
    {name = "ndnr_icecream", price = 93},
    {name = "ndnr_coffee", price = 110},
    {name = "dish_medicinalliquor", price = 118, atl = "images/dish_medicinalliquor.xml"},
    {name = "ndnr_coconutjuice", price = 65},
    {name = "ndnr_creamballsoup", price = 105},
    {name = "ndnr_caviar", price = 105},
    {name = "ndnr_albumenpowder", price = 97},
    {name = "ndnr_tofu", price = 78},
    {name = "ndnr_soybeanmilk1", price = 90},
    {name = "ndnr_soybeanmilk2", price = 110},
    {name = "ndnr_milk", price = 30},
    {name = "ndnr_ice_milk", price = 50},
    {name = "ndnr_dragoonheart", price = 600},
    {name = "ndnr_sharkfin", price = 50},
    {name = "ndnr_scallop", price = 35},
    {name = "ndnr_coffeebeans", price = 20},
    {name = "ndnr_coffeebeans_cooked", price = 22},
    {name = "ndnr_coconut", price = 20},
    {name = "ndnr_coconut_halved", price = 12},
    {name = "ndnr_roe", price = 50},
    {name = "ndnr_iceball", price = 30},
    {name = "ndnr_stinkytofu", price = 108},
    {name = "ndnr_soybean", price = 20}
}

itemlist.selist_cloth_ndnr = {
    {name = "ndnr_armor_snakeskin", price = nil},
    {name = "ndnr_snakeskinhat", price = nil},
    {name = "turf_ndnr_snakeskinfloor", price = nil},
    {name = "ndnr_palmleaf_umbrella", price = nil},
    {name = "ndnr_thatchpack", price = nil},
    {name = "ndnr_aerodynamichat", price = nil},
    {name = "ndnr_pagodasugar", price = nil},
    {name = "ndnr_antivenom", price = nil}
}
itemlist.selist_smithing_ndnr = {
    {name = "ndnr_obsidianaxe", price = nil},
    {name = "ndnr_spear_obsidian", price = nil},
    {name = "ndnr_armorobsidian", price = nil},
    {name = "ndnr_alloyaxe", price = nil},
    {name = "ndnr_alloypickaxe", price = nil},
    {name = "ndnr_alloyshovel", price = nil},
    {name = "ndnr_alloyhammer", price = nil},
    {name = "ndnr_alloyhoe", price = nil},
    {name = "ndnr_alloyspear", price = nil},
    {name = "ndnr_cutlass", price = nil},
    {name = "turf_ndnr_asphalt", price = nil}
}

itemlist.selist_resource_ndnr = {
    {name = "ndnr_snake", price = 150},
    {name = "ndnr_catpoop", price = 30},
    {name = "ndnr_soybean_seeds", price = 50},
    {name = "ndnr_magma_milk", price = 300, tex = "ndnr_magma_milk_0.tex", atl = "images/ndnr_magma_milk_0.xml"},
    {name = "ndnr_weatherpole", price = 500},
    {name = "ndnr_venomgland", price = 40},
    {name = "ndnr_snakeoil", price = 100},
    {name = "ndnr_snakeskin", price = 25},
    {name = "ndnr_dead_swordfish", price = 300},
    {name = "ndnr_obsidian", price = 100},
    {name = "ndnr_alloy", price = 192},
    {name = "ndnr_blue_sporeseed", price = 100, tex = "spore_tall.tex"},
    {name = "ndnr_green_sporeseed", price = 100, tex = "spore_small.tex"},
    {name = "ndnr_red_sporeseed", price = 100, tex = "spore_medium.tex"},
    {name = "ndnr_bigtooth", price = 900},
    {name = "dug_ndnr_coffeebush", price = 100},
    {name = "ndnr_godtoken", price = 500},
    {name = "ndnr_tentacleblood", price = 150},
    {name = "ndnr_palmleaf", price = 20},
    {name = "ndnr_iron", price = 40},
    {name = "ndnr_tar", price = 46},
    {name = "ndnr_roughrock", price = 268}
}

itemlist.selist_precious_ndnr = {
    {name = "ndnr_shark_teethhat", price = nil},
    {name = "ndnr_corruptionstaff", price = nil},
    {name = "ndnr_waterballoon", price = nil},
    {name = "ndnr_opalpreciousamulet", price = 10000},
    {name = "ndnr_quackendrill_item", price = nil},
    {name = "ndnr_quackenbeak", price = 2000},
    {name = "ndnr_energy_core", price = 30000},
    {name = "ndnr_hambat", price = 4030},
    {name = "ndnr_armorvortexcloak", price = 30000},
    {name = "ndnr_waterdrop", price = 1000}
}
itemlist.selist_blueprint_ndnr = {
    {name = "ndnr_smelter_blueprint", price = 2000},
    {name = "ancient_altar_blueprint", price = 2000},
    {name = "ndnr_opalpreciousamulet_blueprint", price = 2000},
    {name = "beebox_hermit_blueprint", price = 2000},
    {name = "meatrack_hermit_blueprint", price = 2000},
    {name = "ndnr_fishfarm_blueprint", price = 2000},
    {name = "tallbirdnest_blueprint", price = 2000},
    {name = "catcoonden_blueprint", price = 2000},
    {name = "pigtorch_blueprint", price = 2000},
    {name = "houndmound_blueprint", price = 2000},
    {name = "monkeybarrel_blueprint", price = 2000},
    {name = "wobster_den_blueprint", price = 2000},
    {name = "moonglass_wobster_den_blueprint", price = 2000},
    {name = "slurtlehole_blueprint", price = 2000},
    {name = "archive_cookpot_blueprint", price = 2000},
    {name = "ndnr_corruptionstaff_blueprint", price = 2000}
}

itemlist.selist_food_Island = {
    {name = "tropicalbouillabaisse", price = 300},
    {name = "sweetpotatosouffle", price = 150},
    {name = "musselbouillabaise", price = 188},
    {name = "coffee", price = 150},
    {name = "coffee_spice_chili", price = 200},
    {name = "coffee_spice_sugar", price = 200},
    {name = "coffee_spice_garlic", price = 200},
    {name = "wobsterbisque", price = 127},
    {name = "bisque", price = 120},
    {name = "wobsterdinner", price = 217},
    {name = "caviar", price = 98},
    {name = "jellyopop", price = 48},
    {name = "sharkfinsoup", price = 111},
    {name = "coconut_halved", price = 10},
    {name = "coconut_cooked", price = 15},
    {name = "sweet_potato", price = 12},
    {name = "sweet_potato_cooked", price = 15},
    {name = "coffeebeans", price = 30},
    {name = "coffeebeans_cooked", price = 35},
    {name = "seaweed", price = 10},
    {name = "seaweed_cooked", price = 12},
    {name = "seaweed_dried", price = 15},
    {name = "roe", price = 50},
    {name = "roe_cooked", price = 20},
    {name = "shark_fin", price = 70},
    {name = "mussel", price = 23},
    {name = "mussel_cooked", price = 28},
    {name = "limpets", price = 25},
    {name = "limpets_cooked", price = 30},
    {name = "jellyfish_dead", price = 20},
    {name = "jellyfish_cooked", price = 25},
    {name = "jellyjerky", price = 30},
    {name = "rainbowjellyfish_dead", price = 65},
    {name = "rainbowjellyfish_cooked", price = 25},
    {name = "neon_quattro", price = 80},
    {name = "neon_quattro_cooked", price = 85},
    {name = "purple_grouper", price = 80},
    {name = "purple_grouper_cooked", price = 85},
    {name = "pierrot_fish", price = 80},
    {name = "pierrot_fish_cooked", price = 85},
    {name = "fish_tropical", price = 40},
    {name = "swordfish_dead", price = 90},
    {name = "solofish_dead", price = 35},
    {name = "lobster", price = 80},
    {name = "lobster_dead", price = 44},
    {name = "lobster_dead_cooked", price = 45},
    {name = "doydoyegg_cooked", price = 50}
}
itemlist.selist_cloth_Island = {
    {name = "palmleaf_umbrella", price = nil},
    {name = "snakeskinhat", price = nil},
    {name = "gashat", price = nil},
    {name = "aerodynamichat", price = nil},
    {name = "shark_teethhat", price = nil},
    {name = "captainhat", price = nil},
    {name = "piratehat", price = nil},
    {name = "armor_snakeskin", price = nil},
    {name = "blubbersuit", price = nil},
    {name = "tarsuit", price = nil},
    {name = "armor_windbreaker", price = nil},
    {name = "armor_lifejacket", price = nil},
    {name = "antivenom", price = nil},
    {name = "poisonbalm", price = nil},
    {name = "thatchpack", price = nil}
}
itemlist.selist_smithing_Island = {
    {name = "spear_poison", price = nil},
    {name = "spear_launcher", price = nil},
    {name = "blowdart_poison", price = nil},
    {name = "cutlass", price = nil},
    {name = "coconade", price = nil},
    {name = "armorlimestone", price = nil},
    {name = "armorcactus", price = nil},
    {name = "armorseashell", price = nil},
    {name = "oxhat", price = nil},
    {name = "machete", price = nil},
    {name = "goldenmachete", price = nil},
    {name = "monkeyball", price = nil},
    {name = "bottlelantern", price = nil},
    {name = "ox_flute", price = nil},
    {name = "boatrepairkit", price = nil},
    {name = "tarlamp", price = nil},
    {name = "surfboard_item", price = 150},
    {name = "boat_torch", price = nil},
    {name = "boat_lantern", price = nil},
    {name = "sail_palmleaf", price = nil},
    {name = "sail_cloth", price = nil},
    {name = "sail_snakeskin", price = nil},
    {name = "boatcannon", price = nil},
    {name = "seatrap", price = nil},
    {name = "trawlnet", price = nil},
    {name = "telescope", price = nil},
    {name = "turf_jungle", price = nil},
    {name = "turf_meadow", price = nil},
    {name = "turf_tidalmarsh", price = nil},
    {name = "turf_magmafield", price = nil},
    {name = "turf_ash", price = nil},
    {name = "turf_volcano", price = nil},
    {name = "turf_snakeskin", price = nil},
    {name = "wall_limestone_item", price = nil},
    {name = "wall_enforcedlimestone_item", price = nil},
    {name = "sandbagsmall_item", price = nil}
}
itemlist.selist_resource_Island = {
    {name = "bamboo", price = 10},
    {name = "fabric", price = 35},
    {name = "vine", price = 12},
    {name = "palmleaf", price = 15},
    {name = "seashell", price = 20},
    {name = "sand", price = 10},
    {name = "ia_messagebottleempty", price = 35},
    {name = "coral", price = 15},
    {name = "limestonenugget", price = 50},
    {name = "corallarve", price = 50},
    {name = "tar", price = 75},
    {name = "dubloon", price = 4},
    {name = "peg_leg", price = 50},
    {name = "needlespear", price = 10},
    {name = "seaweed_stalk", price = 70},
    {name = "dug_bambootree", price = 40},
    {name = "dug_bush_vine", price = 50},
    {name = "dug_elephantcactus", price = 99},
    {name = "dug_coffeebush", price = 240},
    {name = "hail_ice", price = 2},
    {name = "sweet_potato_seeds", price = 25},
    {name = "nubbin", price = nil},
    {name = "mussel_bed", price = nil},
    {name = "jungletreeseed", price = 10},
    {name = "coconut", price = 20},
    {name = "bioluminescence", price = 99},
    {name = "venomgland", price = 40},
    {name = "blowdart_flup", price = 20},
    {name = "snakeskin", price = 20},
    {name = "dorsalfin", price = 50},
    {name = "ox_horn", price = 200},
    {name = "mosquitosack_yellow", price = 40},
    {name = "spoiled_fish_large", price = 10},
    {name = "blubber", price = 40},
    {name = "crab", price = 30},
    {name = "tropical_spider_warrior", price = 200},
    {name = "mosquito_poison", price = 98, tex = "mosquito_yellow.tex"},
    {name = "cormorant", price = 30},
    {name = "seagull", price = 30},
    {name = "toucan", price = 30},
    {name = "parrot", price = 50},
    {name = "parrot_pirate", price = 99},
    {name = "jellyfish", price = 25},
    {name = "rainbowjellyfish", price = 80},
    {name = "pondfish_tropical", price = 45},
    {name = "pondneon_quattro", price = 90},
    {name = "pondpurple_grouper", price = 90},
    {name = "pondpierrot_fish", price = 90}
}
itemlist.selist_precious_Island = {
    {name = "woodlegshat", price = 1200},
    {name = "doydoy", price = 1500},
    {name = "doydoybaby", price = 1200},
    {name = "doydoyegg", price = 600},
    {name = "winter_ornament_boss_doydoy", price = 500},
    {name = "doydoyfeather", price = 200},
    {name = "tropicalfan", price = nil},
    {name = "sail_feather", price = nil},
    {name = "magic_seal", price = 1500},
    {name = "turbine_blades", price = 1500},
    {name = "ironwind", price = nil},
    {name = "quackenbeak", price = 2000},
    {name = "quackendrill", price = nil},
    {name = "quackeringram", price = nil},
    {name = "tigereye", price = 1000},
    {name = "supertelescope", price = nil},
    {name = "shark_gills", price = 1000},
    {name = "double_umbrellahat", price = nil},
    {name = "seasack", price = nil},
    {name = "coral_brain", price = 4000},
    {name = "brainjellyhat", price = 6000},
    {name = "obsidian", price = 150},
    {name = "dragoonheart", price = 300},
    {name = "windstaff", price = nil},
    {name = "wind_conch", price = nil},
    {name = "obsidianaxe", price = nil},
    {name = "obsidianmachete", price = nil},
    {name = "spear_obsidian", price = nil},
    {name = "volcanostaff", price = nil},
    {name = "armorobsidian", price = nil},
    {name = "obsidiancoconade", price = nil},
    {name = "ia_trident", price = 1000},
    {name = "harpoon", price = 500},
    {name = "snakeoil", price = 666},
    {name = "piratepack", price = 1500},
    {name = "earring", price = 2000},
    {name = "ia_messagebottle", price = 1000},
    {name = "mysterymeat", price = 2000},
    {name = "trinket_ia_13", price = 500},
    {name = "trinket_ia_14", price = 500},
    {name = "trinket_ia_15", price = 500},
    {name = "trinket_ia_16", price = 500},
    {name = "trinket_ia_17", price = 500},
    {name = "trinket_ia_18", price = 500},
    {name = "trinket_ia_19", price = 500},
    {name = "trinket_ia_20", price = 500},
    {name = "trinket_ia_21", price = 500},
    {name = "trinket_ia_22", price = 500},
    {name = "trinket_ia_23", price = 500}
}
return itemlist
