return
{
	DESCRIBE_TOODARK = "Eee! Eee! Eee!",
	ANNOUNCE_IS_FEASTING = "EEE EEE!",
	DESCRIBE = 
    {
		CAVE_BANANA = "'Nanas!",
		CAVE_BANANA_COOKED = "'Nanas!",
		CAVE_BANANA_TREE = "'Nanas!",
		CAVE_BANANA_BURNT = "'Nonos!",
		BANANAPOP = "'Nonos!",
		FROZENBANANADAIQUIRI = "'Nonos!",
		BANANABUSH = "'Nanas!",
        DUG_BANANABUSH = "'Nanas!",
		BANANAJUICE = "'Nonos!",
		PLAYER = "Ooooe?",
		WILSON = "Ooooe?",
		WILLOW = "Ooooe?",
		WOLFGANG = "Ooooe?",
		WENDY = "Ooooe?",
		WX78 = "Ooooe?",
		WICKERBOTTOM = "Ooooe?",
		WOODIE = "Ooooe?",
		WAXWELL = "Ooooe?",
		WATHGRITHR = "Ooooe?",
		WEBBER = "Ooooe?",
		WARLY = "Ooooe?",
		WORMWOOD = "Ooooe?",
		WINONA = "Ooooe?",
		WORTOX = "Ooooe?",
		WURT = "Ooooe?",
		WALTER = "Ooooe?",
		WANDA = "Ooooe?",
		WONKEY2 = "Ooooe?"
	},
}