STRINGS.CHARACTER_TITLES.KKR = "可可萝"
STRINGS.CHARACTER_NAMES.kkr = "可可萝"
STRINGS.CHARACTER_DESCRIPTIONS.KKR = "可可萝"
STRINGS.CHARACTER_QUOTES.KKR = "\"可可萝\""
STRINGS.CHARACTER_SURVIVABILITY.kkr = "简单"
STRINGS.CHARACTERS.KKR = require("speech_kkr") 

STRINGS.NAMES.KKR_GEMSTAFF= "宝石杖"
STRINGS.RECIPE_DESC.KKR_GEMSTAFF = "使用宝石制作的新手杖"  --配方上面的描述
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KKR_GEMSTAFF = "使用宝石制作的简单武器"  --人物检查的描述

STRINGS.NAMES.KKR_ELFSTAFF= "精灵之杖"
STRINGS.RECIPE_DESC.KKR_ELFSTAFF = "拥有行动速度加护的新手杖"  --配方上面的描述
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KKR_ELFSTAFF = "它有着风的力量"  --人物检查的描述

STRINGS.NAMES.KKR_ELFSTAFF_PLUS= "大精灵之杖"
STRINGS.RECIPE_DESC.KKR_ELFSTAFF_PLUS = "使用珍贵材料制作的强大武器"  --配方上面的描述
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KKR_ELFSTAFF_PLUS = "充盈着风的力量！"  --人物检查的描述

STRINGS.NAMES.KKR_ELFROBE= "精灵长袍"
STRINGS.RECIPE_DESC.KKR_ELFROBE = "普通的精灵长袍"  --配方上面的描述
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KKR_ELFROBE = "一件普通的精灵长袍"  --人物检查的描述

STRINGS.NAMES.KKR_ELFCLOAK= "大精灵披风"
STRINGS.RECIPE_DESC.KKR_ELFCLOAK = "缠绕着风的力量"  --配方上面的描述
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KKR_ELFCLOAK = "它缠绕着风的力量"  --人物检查的描述


STRINGS.NAMES.KKR_FLOWER_RIBBON= "花朵发饰"
STRINGS.RECIPE_DESC.KKR_FLOWER_RIBBON = "使用花朵简单制作的头饰"  --配方上面的描述
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KKR_FLOWER_RIBBON = "简单的头饰"  --人物检查的描述

STRINGS.NAMES.KKR_FLOWER_AMULET= "花朵护身符"
STRINGS.RECIPE_DESC.KKR_FLOWER_AMULET = "精心制作的头饰"  --配方上面的描述
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KKR_FLOWER_AMULET = "精致的头饰"  --人物检查的描述

STRINGS.NAMES.KKR_AMETH_AMULET= "爱梅斯守护符"
STRINGS.RECIPE_DESC.KKR_AMETH_AMULET = "拥有神明大人加护的花饰"  --配方上面的描述
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KKR_AMETH_AMULET = "艾梅斯大人祝福过的头饰"  --人物检查的描述

STRINGS.NAMES.KKR_NEWYEAR_STAFF= "新春祈福的精灵杖"
STRINGS.RECIPE_DESC.KKR_NEWYEAR_STAFF = "新春祈福的精灵杖"  --配方上面的描述
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KKR_NEWYEAR_STAFF = "新春祈福的精灵杖"  --人物检查的描述

STRINGS.NAMES.KKR_POCKET= "腰包"
STRINGS.RECIPE_DESC.KKR_POCKET = "方便的腰间挎包"  --配方上面的描述
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KKR_POCKET = "便携的腰间包包"  --人物检查的描述

STRINGS.NAMES.KKR_POCKET_PLUS= "大腰包"
STRINGS.RECIPE_DESC.KKR_POCKET_PLUS = "方便的腰间大挎包"  --配方上面的描述
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KKR_POCKET_PLUS = "便携的腰间大包包"  --人物检查的描述

STRINGS.NAMES.KKR_DRAGON_MEAT= "龙尾肉"
STRINGS.RECIPE_DESC.KKR_DRAGON_MEAT = "龙尾肉"  --配方上面的描述
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KKR_DRAGON_MEAT = "龙尾肉"  --人物检查的描述

STRINGS.NAMES.KKR_KANTOSTYLE_STEW= "最高级龙尾关东煮"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KKR_KANTOSTYLE_STEW = "最高级龙尾关东煮"  --人物检查的描述

STRINGS.NAMES.KKR_CACTUS_PANCAKE= "大地仙人掌蜜汁松饼"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KKR_CACTUS_PANCAKE = "大地仙人掌蜜汁松饼"  --人物检查的描述

STRINGS.NAMES.KKR_SEA_SNOWSUGAR= "沧海淡雪糖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KKR_SEA_SNOWSUGAR = "沧海淡雪糖"  --人物检查的描述

STRINGS.NAMES.KKR_CLOUDSEA_MONSTERMEAT= "云海的魔物肉"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KKR_CLOUDSEA_MONSTERMEAT = "沧海淡雪糖"  --人物检查的描述

STRINGS.NAMES.KKR_MEAT= STRINGS.NAMES.MEAT
STRINGS.RECIPE_DESC.MEAT = "取其精华"  --配方上面的描述
STRINGS["ACTIONS"]["CASTAOE"][string["upper"]("kkr_gemstaff")] = "释放冲刺"
STRINGS["ACTIONS"]["CASTAOE"][string["upper"]("kkr_elfstaff")] = "释放冲刺"
STRINGS["ACTIONS"]["CASTAOE"][string["upper"]("kkr_elfstaff_plus")] = "释放冲刺"
