local STRINGS = GLOBAL.STRINGS


STRINGS.NAMES.DES_BCANNON = "Boat Cannon"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DES_BCANNON = "The only thing better than a boat is a boat with a cannon."

STRINGS.CHARACTERS.WILLOW.DESCRIBE.DES_BCANNON = "I wonder if I can start fires with this?"

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.DES_BCANNON = "Is the mightiest weapon!"

STRINGS.CHARACTERS.WENDY.DESCRIBE.DES_BCANNON = "It brings low death to high seas!"

STRINGS.CHARACTERS.WX78.DESCRIBE.DES_BCANNON = "HAHA. NICE"

STRINGS.CHARACTERS.WEBBER.DESCRIBE.DES_BCANNON = "With this we can make a warship!"

STRINGS.CHARACTERS.WOODIE.DESCRIBE.DES_BCANNON = "This'll blow'em up real good!"

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.DES_BCANNON = "I will make a sandhill out of a mountain."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DES_BCANNON = "For combat at sea, I presume."

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.DES_BCANNON = "It's about time I got my hands on one of these."

STRINGS.RECIPE_DESC.DES_BCANNON = "It's got your boat's back."


STRINGS.NAMES.DES_CANNON_STICK = "Cannon Stick"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DES_CANNON_STICK = "Fire in the hole!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.DES_CANNON_STICK = "Fire in the hole!"
STRINGS.RECIPE_DESC.DES_CANNON_STICK = "Shoot the cannon!"

STRINGS.NAMES.DES_CB_GROUND_STONE = "Rock Cannonball"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DES_CB_GROUND_STONE = "I will need a cannon to use that properly."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.DES_CB_GROUND_STONE = "Now, I need a cannon!"
STRINGS.RECIPE_DESC.DES_CB_GROUND_STONE = "Rocky-rocky cannonball!"

STRINGS.NAMES.DES_CB_GROUND_RED = "Fire Cannonball"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DES_CB_GROUND_RED = "Don't play with the matches!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.DES_CB_GROUND_RED = "Oh, my favourite!"
STRINGS.RECIPE_DESC.DES_CB_GROUND_RED = "Complete with greek fire!"

STRINGS.NAMES.DES_CB_GROUND_GLASS = "Glassshard Cannonball"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DES_CB_GROUND_GLASS = "I don't want to be near once it's explodes!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.DES_CB_GROUND_GLASS = "Not fire-y? Not funny!"
STRINGS.RECIPE_DESC.DES_CB_GROUND_GLASS = "Beware the shrapnel!"

STRINGS.NAMES.GT_BOAT_SPOTLIGHT = "Boat Floodlight"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GT_BOAT_SPOTLIGHT = "Lightray follows the steering wheel!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GT_BOAT_SPOTLIGHT = "Bright"
STRINGS.RECIPE_DESC.GT_BOAT_SPOTLIGHT = "It follows steering wheel!"

STRINGS.NAMES.GT_BOAT_SPOTLIGHT_MOON = "Moon Floodlight"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GT_BOAT_SPOTLIGHT_MOON = "Moon follows the steering wheel!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GT_BOAT_SPOTLIGHT_MOON = "Bright"
STRINGS.RECIPE_DESC.GT_BOAT_SPOTLIGHT_MOON = "It follows steering wheel!"

STRINGS.NAMES.DES_BOAT_TORCH = "Boat Light"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DES_BOAT_TORCH = "A torch!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.DES_BOAT_TORCH = "A torch!"
STRINGS.RECIPE_DESC.DES_BOAT_TORCH = "Bunch of lights for your boat!"

STRINGS.NAMES.GT_STEAM_ENGINE = "Turbine Engine"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GT_STEAM_ENGINE = "Turbine Engine!"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GT_STEAM_ENGINE = "Turbine Engine!"
STRINGS.RECIPE_DESC.GT_STEAM_ENGINE = "Steampunk on the seas!"

