local STRINGS = GLOBAL.STRINGS


STRINGS.NAMES.DES_BCANNON = "舰船加农炮"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DES_BCANNON = "除了船只之外，带有加农炮的船是最好的。"

STRINGS.CHARACTERS.WILLOW.DESCRIBE.DES_BCANNON = "我想知道我能否用这个点火。"

STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.DES_BCANNON = "这是最强大的武器！"

STRINGS.CHARACTERS.WENDY.DESCRIBE.DES_BCANNON = "它给高海域带来了低沉的死亡！"

STRINGS.CHARACTERS.WX78.DESCRIBE.DES_BCANNON = "哈哈，不错"

STRINGS.CHARACTERS.WEBBER.DESCRIBE.DES_BCANNON = "有了这个我们可以制造一艘战舰！"

STRINGS.CHARACTERS.WOODIE.DESCRIBE.DES_BCANNON = "这会把敌人炸得干净利落！"

STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.DES_BCANNON = "我将用山丘制造一座山。"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DES_BCANNON = "为了海战，我推测如此。"

STRINGS.CHARACTERS.WAXWELL.DESCRIBE.DES_BCANNON = "我终于得到其中之一的机会了。"

STRINGS.RECIPE_DESC.DES_BCANNON = "它保护着你的船只。"



STRINGS.NAMES.DES_CANNON_STICK = "火炮指示"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DES_CANNON_STICK = "引线着火！"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.DES_CANNON_STICK = "引线着火！"
STRINGS.RECIPE_DESC.DES_CANNON_STICK = "用来射击火炮！"

STRINGS.NAMES.DES_CB_GROUND_STONE = "岩石炮弹"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DES_CB_GROUND_STONE = "我需要个火炮才能好好使用它。"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.DES_CB_GROUND_STONE = "现在，我需要个火炮！"
STRINGS.RECIPE_DESC.DES_CB_GROUND_STONE = "岩石火炮弹！"

STRINGS.NAMES.DES_CB_GROUND_RED = "火焰火炮弹"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DES_CB_GROUND_RED = "别拿火柴玩了！"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.DES_CB_GROUND_RED = "哦，我的最爱！"
STRINGS.RECIPE_DESC.DES_CB_GROUND_RED = "带有希腊火的火炮弹！"

STRINGS.NAMES.DES_CB_GROUND_GLASS = "玻璃碎片炮弹"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DES_CB_GROUND_GLASS = "一旦爆炸，我可不想靠近！"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.DES_CB_GROUND_GLASS = "不着火？不好玩！"
STRINGS.RECIPE_DESC.DES_CB_GROUND_GLASS = "小心碎片飞溅！"











STRINGS.NAMES.GT_BOAT_SPOTLIGHT = "舰船聚光灯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GT_BOAT_SPOTLIGHT = "光束随舵轮移动！"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GT_BOAT_SPOTLIGHT = "明亮"
STRINGS.RECIPE_DESC.GT_BOAT_SPOTLIGHT = "跟随舵轮移动！"

STRINGS.NAMES.GT_BOAT_SPOTLIGHT_MOON = "月亮聚光灯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GT_BOAT_SPOTLIGHT_MOON = "月亮随舵轮移动！"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GT_BOAT_SPOTLIGHT_MOON = "明亮"
STRINGS.RECIPE_DESC.GT_BOAT_SPOTLIGHT_MOON = "更明亮，跟随舵轮移动！"

STRINGS.NAMES.DES_BOAT_TORCH = "舰船灯笼"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DES_BOAT_TORCH = "一把火炬！"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.DES_BOAT_TORCH = "一把火炬！"
STRINGS.RECIPE_DESC.DES_BOAT_TORCH = "为你的舰船提供小范围灯光！"

STRINGS.NAMES.GT_STEAM_ENGINE = "蒸汽引擎"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GT_STEAM_ENGINE = "蒸汽引擎！"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.GT_STEAM_ENGINE = "蒸汽引擎！"
STRINGS.RECIPE_DESC.GT_STEAM_ENGINE = "强大的动力，海上的蒸汽朋克！"

